### ISSUE TITLE
Import Error, when trying to import dreal module into python3.7

### ISSUE THREAD

**Issue by GDelimpa** [dreal/dreal4#102]
So I run:

>import dreal

or

> from dreal.api import CheckSatisfiability, Minimize

with python3.7, and I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gdelimpaltadak/dreal4/opt/dreal/4.18.08.1/lib/python3/site-packages/dreal/__init__.py", line 2, in <module>
    from dreal.util import *
  File "/Users/gdelimpaltadak/dreal4/opt/dreal/4.18.08.1/lib/python3/site-packages/dreal/util/__init__.py", line 1, in <module>
    from dreal.util._dreal_util_py import *
ImportError: dlopen(/Users/gdelimpaltadak/dreal4/opt/dreal/4.18.08.1/lib/python3/site-packages/dreal/util/_dreal_util_py.so, 2): Symbol not found: __ZNK5dreal3Box12has_variableERKNS_5drake8symbolic8VariableE
  Referenced from: /Users/gdelimpaltadak/dreal4/opt/dreal/4.18.08.1/lib/python3/site-packages/dreal/util/_dreal_util_py.so
  Expected in: /usr/local/lib/libdreal.so
 in /Users/gdelimpaltadak/dreal4/opt/dreal/4.18.08.1/lib/python3/site-packages/dreal/util/_dreal_util_py.so

I have already done the procedure needed for python3 bindings, so I don't know why I get this error.

**Comment by soonho-tri** [comment]
Can you try the following?

```
export LD_LIBRARY_PATH=/Users/gdelimpaltadak/dreal4/opt/dreal/4.18.08.1/lib/:${LD_LIBRARY_PATH}
```
then, please run `python3` and test it again.

**Comment by GDelimpa** [comment]
Thank you very much! It worked, when running python3.7 from terminal.
But now that I am trying to run the same thing from spyder (which also runs with python 3.7, and is installed via anaconda) it gives me the same error. What would you suggest? Thanks in advcance!

**Comment by soonho-tri** [comment]
> Thank you very much! It worked, when running python3.7 from terminal.

Good to know. I'll update the `README.md` file.

> But now that I am trying to run the same thing from spyder (which also runs with python 3.7, and is installed via anaconda) it gives me the same error. What would you suggest? Thanks in advcance!

Sorry, I am not sure that I can help. I don't know even what `spyder` is.

**Comment by GDelimpa** [comment]
Spyder is an IDE for python, mostly used for scientific work. It gives me the following similar error:
ImportError: dlopen(/Users/gdelimpaltadak/anaconda3/lib/python3.7/site-packages/dreal/util/_dreal_util_py.so, 2): Symbol not found: __ZNK5dreal3Box12has_variableERKNS_5drake8symbolic8VariableE
  Referenced from: /Users/gdelimpaltadak/anaconda3/lib/python3.7/site-packages/dreal/util/_dreal_util_py.so
  Expected in: /usr/local/lib/libdreal.so
 in /Users/gdelimpaltadak/anaconda3/lib/python3.7/site-packages/dreal/util/_dreal_util_py.so

Do you think there might be a similar way of fixing it? Thank you :)

**Comment by soonho-tri** [comment]
It seems that adding the line `export LD_LIBRARY_PATH=...` to `~/.bashrc` can help?
https://groups.google.com/d/msg/spyderlib/zUPW9O-wViM/Tar7ywEHCgAJ

**Comment by GDelimpa** [comment]
@soonho-tri Thanks for your help. I also have an update for the original problem.
So, if I do all the procedure for python3 bindings and run the export LD_LIBRARY_PATH=... command, I told you that there is no problem importing the modules to python3. 
The thing is that when I close the terminal, and open a new terminal session, python3 cannot find the dreal module. And I have to redo it all over again...

**Comment by soonho-tri** [comment]
> The thing is that when I close the terminal, and open a new terminal session, python3 cannot find the dreal module.

Adding the line export LD_LIBRARY_PATH=... to ~/.bashrc (or other file if you using a different shell) should give you a consistent experience.

**Comment by GDelimpa** [comment]
But the thing is that when I start a new terminal session, even when I run the export PYTHONPATH and the export LD_LIBRARY_PATH commands, python3 does not find the dreal module. It seems that I have to run the following commands first:
>bazel build //:archive --force_python=py3 --python_path=python3
>tar xvfz bazel-bin/archive.tar.gz
I thought that this is strange. Why would I have to build again, after terminating the previous terminal session?

**Comment by soonho-tri** [comment]
1. For sure, you shouldn't include the `bazel build` and `tar xvfz` in any of your bash files.
2. The two `export` lines look good to me. Do you mean that `python3` still fails to find `dreal` after opening a new terminal session?

**Comment by GDelimpa** [comment]
@soonho-tri Now that I have added those two lines in the .bash_profile file, there is no problem at all, when running python3 through the terminal.
Nevertheless there is still the following problem: Even if you run the spyder IDE directly from the terminal (and not e.g. from the anaconda app), which I think it means it uses the same shell as if you would run python3 from a terminal, it gives you the aforementioned Import Error. But why does this happen? I mean, if you run python3 from the terminal it is all fine, but if you run spyder from the same terminal, suddenly the error comes up again.

**Comment by soonho-tri** [comment]
> Now that I have added those two lines in the .bash_profile file, there is no problem at all, when running python3 through the terminal.

Great.

> Nevertheless there is still the following problem: Even if you run the spyder IDE directly from the terminal (and not e.g. from the anaconda app), which I think it means it uses the same shell as if you would run python3 from a terminal, it gives you the aforementioned Import Error. But why does this happen? I mean, if you run python3 from the terminal it is all fine, but if you run spyder from the same terminal, suddenly the error comes up again.

I suspect that it's a spyder issue, not respecting the environment variables. Can you contact the team?

**Comment by soonho-tri** [comment]
I've updated the `README.md` by a7e60c60eaa1188923d5791f3bd91e6127423aea.
