### ISSUE TITLE
SymPy and dreal in Python

### ISSUE THREAD

**Issue by GDelimpa** [dreal/dreal4#104]
I would like to ask you if there is a piece of code which could facilitate the transformation of SymPy (symbolic toolbox of python) variables and expressions to dreal expressions. I saw that there is a particular script, where a lot of new classes are defined, but I don't know how I could use that. Thanks in advance! :)

**Comment by soonho-tri** [comment]
To my knowledge, we don't have such a script for that. I guess one can write it, but I don't have a plan for that for now.
