### ISSUE TITLE
Print asserted formulas in SMTLIB format?

### ISSUE THREAD

**Issue by caballa** [dreal/dreal4#105]
Is it possible to print the asserted formulas in some kind of SMT-LIB format?

**Comment by soonho-tri** [comment]
We do not have this feature for now, but I can add one.

**Comment by caballa** [comment]
Thanks, that would be very useful.

**Comment by soonho-tri** [comment]
FYI, I've added `ToPrefix(expression)` / `ToPrefix(formula)` in C++, and `expression.ToPrefix()` and `formula.ToPrefix()` in Python APIs.

**Comment by soonho-tri** [comment]
I'll add a method to `Context` class, e.g. `Context::GetAssertions`, which will give you a list of asserted formulas.

Are you using dReal in C++ or Python? If it's the latter, I need to expose the `Context` class to the Python side.

**Comment by caballa** [comment]
I use C++

**Comment by soonho-tri** [comment]
Done. Please check https://github.com/dreal/dreal4/blob/master/dreal/solver/test/context_test.cc#L28-L46.

Note that bound constraints such as `x <= 5` are not stored as assertions as shown in the test code.

**Comment by soonho-tri** [comment]
Closed by 63df044be55122172e371fed5deba8b1c6349764
