### ISSUE TITLE
`dreal/util/scoped_vector.h` file not found

### ISSUE THREAD

**Issue by caballa** [dreal/dreal4#111]
I'm using dreal from an external app.
I built dreal using `bazel build //:archive`.

**Comment by soonho-tri** [comment]
Thanks for the report. I will add it soon.

**Comment by soonho-tri** [comment]
Can you check if 6cbfafdd79e841dec89270cd2bdba41d54f47b66 fixes your problem?

**Comment by caballa** [comment]
It does. Thanks!
