### ISSUE TITLE
Many undefined reference to filib

### ISSUE THREAD

**Issue by nima-roohi** [dreal/dreal4#117]
On ubuntu 18.04, I receive many errors like the following:

```
~/Downloads/dreal4-4.18.11.4/bazel-bin/libdreal.so: undefined reference to `filib::filib_consts<double>::q_ccsm`
```

Where can I find the filib library?

**Comment by soonho-tri** [comment]
Have you followed the instructions at https://github.com/dreal/dreal4#install-prerequsites ?

**Comment by nima-roohi** [comment]
Yes, I did,
I think the main problem was that I was using an incorrect version of ibex.
It is working now.

**Comment by soonho-tri** [comment]
👍
