### ISSUE TITLE
Build error on MacOS 10.14.1 : use of old-style cast [-Werror,-Wold-style-cast]

### ISSUE THREAD

**Issue by YaChienChang** [dreal/dreal4#121]
- OS version: 
ProductName:	Mac OS X
ProductVersion:	10.14.1
BuildVersion:	18B75

- Compiler:
LLVM version 10.0.0 (clang-1000.10.44.4)

- Bazel version: 
Build label: 0.23.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Feb 26 17:41:30 2019 (1551202890)
Build timestamp: 1551202890
Build timestamp as int: 1551202890

- Build commit: 
4ff5354 (HEAD -> master, origin/master, origin/HEAD) bazel: Use --python_version instead of --force_python

```
ERROR: /Users/vanessa/dreal4/dreal/contractor/BUILD.bazel:60:1: C++ compilation of rule '//dreal/contractor:counterexample_refiner' failed (Exit 1) cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 117 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from dreal/contractor/counterexample_refiner.cc:1:
In file included from ./dreal/contractor/counterexample_refiner.h:6:
In file included from ./dreal/optimization/nlopt_optimizer.h:8:
/usr/local/include/nlopt.hpp:40:42: error: use of old-style cast [-Werror,-Wold-style-cast]
      return nlopt_get_initial_step(opt, (const double *) NULL, dx);
                                         ^                ~~~~
/usr/local/include/nlopt.hpp:158:24: error: use of old-style cast [-Werror,-Wold-style-cast]
      myfunc_data *d = (myfunc_data *) p;
                       ^               ~
/usr/local/include/nlopt.hpp:166:24: error: use of old-style cast [-Werror,-Wold-style-cast]
      myfunc_data *d = (myfunc_data *) p;
                       ^               ~
/usr/local/include/nlopt.hpp:180:9: error: use of old-style cast [-Werror,-Wold-style-cast]
        return (void*) dnew;
               ^       ~~~~
4 errors generated.
INFO: Elapsed time: 5.918s, Critical Path: 5.28s
INFO: 16 processes: 16 darwin-sandbox.
FAILED: Build did NOT complete successfully
```
I found the [similar issue](https://github.com/RobotLocomotion/drake/issues/10129#issuecomment-444978446) and tried to use export BAZEL_USE_CPP_ONLY_TOOLCHAIN=1, but it didn't work. Thanks for your time :)

**Comment by soonho-tri** [comment]
1) Do `bazel clean --expunge` and `bazel build //...` help?
2) Please run `bazel build //... --announce_rc` and copy/paste the rc options it reads (e.g. `Reading rc options...`)
3) What's your `echo $CC` and `echo $CXX`?
4) `BAZEL_USE_CPP_ONLY_TOOLCHAIN=1` shouldn't be used. Try `unset BAZEL_USE_CPP_ONLY_TOOLCHAIN`.

**Comment by YaChienChang** [comment]
Hi Soonho, Thanks for your immediate help.
1. ```bazel clean --expunge``` and ```bazel build //...``` didn't work, it came out the same error info.
2. Reading rc options for 'build' from /Users/vanessa/dreal4/.bazelrc:
  'build' options: --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 -c opt --force_pic --strip=never --strict_system_includes
3. My `echo $CC` and `echo $CXX` are not set. Should I set it?
I tried `export CC=/usr/bin/clang` and `export CXX=/usr/bin/clang`, then ran `bazel clean --expunge` and ```bazel build //...``` . But, I got same previous error .
4. Tried it, but it's still failed.

**Comment by soonho-tri** [comment]
Can you send me the output of `bazel build //... --announce_rc --verbose_failures` (via email)?

**Comment by YaChienChang** [comment]
Hi Soonho,
Here is the output :

Starting local Bazel server and connecting to it...

INFO: Options provided by the client:

  Inherited 'common' options: --isatty=1 --terminal_columns=80

INFO: Reading rc options for 'build' from /Users/vanessa/dreal4/.bazelrc:

  'build' options: --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 -c opt
--force_pic --strip=never --strict_system_includes

INFO: Analysed 397 targets (65 packages loaded, 2685 targets configured).

INFO: Found 397 targets...

INFO: From Linking
third_party/com_github_robotlocomotion_drake/libdrake_symbolic.a:

/Library/Developer/CommandLineTools/usr/bin/libtool: file:
bazel-out/darwin-opt/bin/third_party/com_github_robotlocomotion_drake/_objs/drake_symbolic/symbolic_expression_visitor.pic.o
has no symbols

/Library/Developer/CommandLineTools/usr/bin/libtool: file:
bazel-out/darwin-opt/bin/third_party/com_github_robotlocomotion_drake/_objs/drake_symbolic/symbolic_formula_visitor.pic.o
has no symbols

ERROR: /Users/vanessa/dreal4/dreal/contractor/BUILD.bazel:60:1: C++
compilation of rule '//dreal/contractor:counterexample_refiner' failed
(Exit 1) cc_wrapper.sh failed: error executing command

  (cd
/private/var/tmp/_bazel_vanessa/fdaeea53d5e04bbac79f78a0a5771883/sandbox/darwin-sandbox/17/execroot/dreal
&& \

  exec env - \

    PATH=/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin \

    PWD=/proc/self/cwd \

  external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE
-fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics
-fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG
-ffunction-sections -fdata-sections '-std=c++0x' -MD -MF
bazel-out/darwin-opt/bin/dreal/contractor/_objs/counterexample_refiner/counterexample_refiner.pic.d
'-frandom-seed=bazel-out/darwin-opt/bin/dreal/contractor/_objs/counterexample_refiner/counterexample_refiner.pic.o'
-fPIC '-DFMT_HEADER_ONLY=1' -DSPDLOG_FMT_EXTERNAL -iquote . -iquote
bazel-out/darwin-opt/genfiles -iquote bazel-out/darwin-opt/bin -iquote
external/fmt -iquote bazel-out/darwin-opt/genfiles/external/fmt -iquote
bazel-out/darwin-opt/bin/external/fmt -iquote external/spdlog -iquote
bazel-out/darwin-opt/genfiles/external/spdlog -iquote
bazel-out/darwin-opt/bin/external/spdlog -iquote external/ibex -iquote
bazel-out/darwin-opt/genfiles/external/ibex -iquote
bazel-out/darwin-opt/bin/external/ibex -iquote external/nlopt -iquote
bazel-out/darwin-opt/genfiles/external/nlopt -iquote
bazel-out/darwin-opt/bin/external/nlopt -isystem external/fmt/include
-isystem bazel-out/darwin-opt/genfiles/external/fmt/include -isystem
bazel-out/darwin-opt/bin/external/fmt/include -isystem
external/spdlog/include -isystem
bazel-out/darwin-opt/genfiles/external/spdlog/include -isystem
bazel-out/darwin-opt/bin/external/spdlog/include -isystem
third_party/com_github_robotlocomotion_drake -isystem
bazel-out/darwin-opt/genfiles/third_party/com_github_robotlocomotion_drake
-isystem
bazel-out/darwin-opt/bin/third_party/com_github_robotlocomotion_drake
-isystem external/ibex/include/_usr_local_opt_ibex@2.7.4_include -isystem
bazel-out/darwin-opt/genfiles/external/ibex/include/_usr_local_opt_ibex@2.7.4_include
-isystem
bazel-out/darwin-opt/bin/external/ibex/include/_usr_local_opt_ibex@2.7.4_include
-isystem external/ibex/include/_usr_local_opt_ibex@2.7.4_include_ibex
-isystem
bazel-out/darwin-opt/genfiles/external/ibex/include/_usr_local_opt_ibex@2.7.4_include_ibex
-isystem
bazel-out/darwin-opt/bin/external/ibex/include/_usr_local_opt_ibex@2.7.4_include_ibex
-isystem external/ibex/include/_usr_local_opt_ibex@2.7.4_include_ibex_3rd
-isystem
bazel-out/darwin-opt/genfiles/external/ibex/include/_usr_local_opt_ibex@2.7.4_include_ibex_3rd
-isystem
bazel-out/darwin-opt/bin/external/ibex/include/_usr_local_opt_ibex@2.7.4_include_ibex_3rd
-isystem external/ibex/include/_usr_local_opt_clp_include_clp_coin -isystem
bazel-out/darwin-opt/genfiles/external/ibex/include/_usr_local_opt_clp_include_clp_coin
-isystem
bazel-out/darwin-opt/bin/external/ibex/include/_usr_local_opt_clp_include_clp_coin
-isystem
external/ibex/include/_usr_local_opt_coinutils_include_coinutils_coin
-isystem
bazel-out/darwin-opt/genfiles/external/ibex/include/_usr_local_opt_coinutils_include_coinutils_coin
-isystem
bazel-out/darwin-opt/bin/external/ibex/include/_usr_local_opt_coinutils_include_coinutils_coin
-isystem external/nlopt/include/_usr_local_Cellar_nlopt_2.4.2_2_include
-isystem
bazel-out/darwin-opt/genfiles/external/nlopt/include/_usr_local_Cellar_nlopt_2.4.2_2_include
-isystem
bazel-out/darwin-opt/bin/external/nlopt/include/_usr_local_Cellar_nlopt_2.4.2_2_include
'-std=c++14' '-Werror=all' '-Werror=attributes' '-Werror=deprecated'
'-Werror=deprecated-declarations' '-Werror=ignored-qualifiers'
'-Werror=old-style-cast' '-Werror=overloaded-virtual' '-Werror=shadow'
'-Werror=absolute-value' '-Werror=inconsistent-missing-override'
'-Werror=non-virtual-dtor' '-Werror=return-stack-address'
'-Werror=sign-compare' -no-canonical-prefixes -Wno-builtin-macro-redefined
'-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"'
'-D__TIME__="redacted"' -c dreal/contractor/counterexample_refiner.cc -o
bazel-out/darwin-opt/bin/dreal/contractor/_objs/counterexample_refiner/counterexample_refiner.pic.o)

Execution platform: @bazel_tools//platforms:host_platform


Use --sandbox_debug to see verbose messages from the sandbox: cc_wrapper.sh
failed: error executing command

  (cd
/private/var/tmp/_bazel_vanessa/fdaeea53d5e04bbac79f78a0a5771883/sandbox/darwin-sandbox/17/execroot/dreal
&& \

  exec env - \

    PATH=/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin \

    PWD=/proc/self/cwd \

  external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE
-fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics
-fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG
-ffunction-sections -fdata-sections '-std=c++0x' -MD -MF
bazel-out/darwin-opt/bin/dreal/contractor/_objs/counterexample_refiner/counterexample_refiner.pic.d
'-frandom-seed=bazel-out/darwin-opt/bin/dreal/contractor/_objs/counterexample_refiner/counterexample_refiner.pic.o'
-fPIC '-DFMT_HEADER_ONLY=1' -DSPDLOG_FMT_EXTERNAL -iquote . -iquote
bazel-out/darwin-opt/genfiles -iquote bazel-out/darwin-opt/bin -iquote
external/fmt -iquote bazel-out/darwin-opt/genfiles/external/fmt -iquote
bazel-out/darwin-opt/bin/external/fmt -iquote external/spdlog -iquote
bazel-out/darwin-opt/genfiles/external/spdlog -iquote
bazel-out/darwin-opt/bin/external/spdlog -iquote external/ibex -iquote
bazel-out/darwin-opt/genfiles/external/ibex -iquote
bazel-out/darwin-opt/bin/external/ibex -iquote external/nlopt -iquote
bazel-out/darwin-opt/genfiles/external/nlopt -iquote
bazel-out/darwin-opt/bin/external/nlopt -isystem external/fmt/include
-isystem bazel-out/darwin-opt/genfiles/external/fmt/include -isystem
bazel-out/darwin-opt/bin/external/fmt/include -isystem
external/spdlog/include -isystem
bazel-out/darwin-opt/genfiles/external/spdlog/include -isystem
bazel-out/darwin-opt/bin/external/spdlog/include -isystem
third_party/com_github_robotlocomotion_drake -isystem
bazel-out/darwin-opt/genfiles/third_party/com_github_robotlocomotion_drake
-isystem
bazel-out/darwin-opt/bin/third_party/com_github_robotlocomotion_drake
-isystem external/ibex/include/_usr_local_opt_ibex@2.7.4_include -isystem
bazel-out/darwin-opt/genfiles/external/ibex/include/_usr_local_opt_ibex@2.7.4_include
-isystem
bazel-out/darwin-opt/bin/external/ibex/include/_usr_local_opt_ibex@2.7.4_include
-isystem external/ibex/include/_usr_local_opt_ibex@2.7.4_include_ibex
-isystem
bazel-out/darwin-opt/genfiles/external/ibex/include/_usr_local_opt_ibex@2.7.4_include_ibex
-isystem
bazel-out/darwin-opt/bin/external/ibex/include/_usr_local_opt_ibex@2.7.4_include_ibex
-isystem external/ibex/include/_usr_local_opt_ibex@2.7.4_include_ibex_3rd
-isystem
bazel-out/darwin-opt/genfiles/external/ibex/include/_usr_local_opt_ibex@2.7.4_include_ibex_3rd
-isystem
bazel-out/darwin-opt/bin/external/ibex/include/_usr_local_opt_ibex@2.7.4_include_ibex_3rd
-isystem external/ibex/include/_usr_local_opt_clp_include_clp_coin -isystem
bazel-out/darwin-opt/genfiles/external/ibex/include/_usr_local_opt_clp_include_clp_coin
-isystem
bazel-out/darwin-opt/bin/external/ibex/include/_usr_local_opt_clp_include_clp_coin
-isystem
external/ibex/include/_usr_local_opt_coinutils_include_coinutils_coin
-isystem
bazel-out/darwin-opt/genfiles/external/ibex/include/_usr_local_opt_coinutils_include_coinutils_coin
-isystem
bazel-out/darwin-opt/bin/external/ibex/include/_usr_local_opt_coinutils_include_coinutils_coin
-isystem external/nlopt/include/_usr_local_Cellar_nlopt_2.4.2_2_include
-isystem
bazel-out/darwin-opt/genfiles/external/nlopt/include/_usr_local_Cellar_nlopt_2.4.2_2_include
-isystem
bazel-out/darwin-opt/bin/external/nlopt/include/_usr_local_Cellar_nlopt_2.4.2_2_include
'-std=c++14' '-Werror=all' '-Werror=attributes' '-Werror=deprecated'
'-Werror=deprecated-declarations' '-Werror=ignored-qualifiers'
'-Werror=old-style-cast' '-Werror=overloaded-virtual' '-Werror=shadow'
'-Werror=absolute-value' '-Werror=inconsistent-missing-override'
'-Werror=non-virtual-dtor' '-Werror=return-stack-address'
'-Werror=sign-compare' -no-canonical-prefixes -Wno-builtin-macro-redefined
'-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"'
'-D__TIME__="redacted"' -c dreal/contractor/counterexample_refiner.cc -o
bazel-out/darwin-opt/bin/dreal/contractor/_objs/counterexample_refiner/counterexample_refiner.pic.o)

Execution platform: @bazel_tools//platforms:host_platform


Use --sandbox_debug to see verbose messages from the sandbox

In file included from dreal/contractor/counterexample_refiner.cc:1:

In file included from ./dreal/contractor/counterexample_refiner.h:6:

In file included from ./dreal/optimization/nlopt_optimizer.h:8:

/usr/local/include/nlopt.hpp:40:42: error: use of old-style cast
[-Werror,-Wold-style-cast]

      return nlopt_get_initial_step(opt, (const double *) NULL, dx);

                                         ^                ~~~~

/usr/local/include/nlopt.hpp:158:24: error: use of old-style cast
[-Werror,-Wold-style-cast]

      myfunc_data *d = (myfunc_data *) p;

                       ^               ~

/usr/local/include/nlopt.hpp:166:24: error: use of old-style cast
[-Werror,-Wold-style-cast]

      myfunc_data *d = (myfunc_data *) p;

                       ^               ~

/usr/local/include/nlopt.hpp:180:9: error: use of old-style cast
[-Werror,-Wold-style-cast]

        return (void*) dnew;

               ^       ~~~~

4 errors generated.

INFO: Elapsed time: 13.009s, Critical Path: 6.34s

INFO: 21 processes: 21 darwin-sandbox.

FAILED: Build did NOT complete successfully

Thanks a lot :)

Ya-Chien

Soonho Kong <notifications@github.com> 於 2019年3月9日 週六 下午3:43寫道：

**Comment by soonho-tri** [comment]
For the record, it was due to missing Xcode installation. `xcode-select -p` should return `/Applications/Xcode.app/Contents/Developer`.
