### ISSUE TITLE
"And" is not defined

### ISSUE THREAD

**Issue by huangl223** [dreal/dreal4#125]
After following the instruction to install dreal4 python package on Ubuntu v18.06, I start to test the dreal package by using the example given at  https://github.com/dreal/dreal4:
from dreal import *

x = Variable("x")
y = Variable("y")
z = Variable("z")

f_sat = And(0 <= x, x <= 10,
            0 <= y, y <= 10,
            0 <= z, z <= 10,
            sin(x) + cos(y) == z)

result = CheckSatisfiability(f_sat, 0.001)
print(result)

However, python shows the error:
File ".../dreal-test-2.py", line 7, in <module>
    f_sat = And(0 <= x, x <= 10,
NameError: name 'And' is not defined

Is it because there is other neccessary python package that haven't been installed except dreal4?

**Comment by huangl223** [comment]
huangl223@ubuntu:~$ import dreal
huangl223@ubuntu:~$ dreal

Command 'dreal' not found, but can be installed with:

sudo apt install alliance

huangl223@ubuntu:~$ dir(dreal)
bash: syntax error near unexpected token `dreal'
huangl223@ubuntu:~$

**Comment by huangl223** [comment]
When I add the following code in the python file (before the logical formula), I can run the example correctly:

from dreal._dreal_py import __logical_and, __logical_or


def logical_and(*formulas):
    assert len(formulas) >= 1, "Must supply at least one operand"
    return reduce(__logical_and, formulas)


def logical_or(*formulas):
    assert len(formulas) >= 1, "Must supply at least one operand"
    return reduce(__logical_or, formulas)


# Add aliases
And = logical_and
Or = logical_or
Not = logical_not
Iff = logical_iff
Implies = logical_imply

**Comment by soonho-tri** [comment]
OK. I was not clear enough. Can you run the following in your python interpreter?

```python
import dreal
dreal
dir(dreal)
```

I have:
```
>>> import dreal
>>> dreal
<module 'dreal' from '.../Library/Python/2.7/lib/python/site-packages/dreal/__init__.pyc'>
>>> dir(dreal)
['And', 'Box', 'CheckSatisfiability', 'Config', 'Context', 'Expression', 'Formula', 'Iff', 'Implies', 'Interval', 'LogLevel', 'Logic', 'Minimize', 'Not', 'Or', 'Variable', 'Variables', '__builtins__', '__doc__', '__file__', '__logical_and', '__logical_or', '__name__', '__package__', '__path__', '_dreal_py', 'abs', 'absolute_import', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cos', 'cosh', 'distance', 'div2', 'division', 'exp', 'forall', 'if_then_else', 'integer', 'intersect', 'log', 'logical_and', 'logical_iff', 'logical_imply', 'logical_not', 'logical_or', 'max', 'min', 'pow', 'print_function', 'reduce', 'root', 'set_log_level', 'sign', 'sin', 'sinh', 'sqr', 'sqrt', 'tan', 'tanh']
>>>
```

**Comment by huangl223** [comment]
`>>> import dreal
>>> dreal
<module 'dreal' from '/home/huangl223/.local/lib/python2.7/site-packages/dreal/__init__.pyc'>
>>> dir(dreal)
['Box', 'CheckSatisfiability', 'Config', 'Context', 'Expression', 'Formula', 'Interval', 'LogLevel', 'Logic', 'Minimize', 'Variable', 'Variables', '__builtins__', '__doc__', '__file__', '__logical_and', '__logical_or', '__name__', '__package__', '__path__', '_dreal_py', 'abs', 'absolute_import', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cos', 'cosh', 'distance', 'div2', 'division', 'exp', 'forall', 'if_then_else', 'integer', 'intersect', 'log', 'logical_and', 'logical_iff', 'logical_imply', 'logical_not', 'logical_or', 'max', 'min', 'pow', 'print_function', 'reduce', 'root', 'set_log_level', 'sign', 'sin', 'sinh', 'sqr', 'sqrt', 'tan', 'tanh']
`

**Comment by soonho-tri** [comment]
I'm afraid that you're running an old version. Can you try `pip install dreal --user --upgrade` and check `dir(dreal)` includes `And`?

**Comment by soonho-tri** [comment]
Never mind. I can actually reproduce the problem on an Ubuntu machine. I'll fix the problem.

**Comment by soonho-tri** [comment]
I've uploaded `4.19.4.1` in PyPI, https://pypi.org/project/dreal/. Please do `pip install dreal --upgrade` to install the latest version.
