### ISSUE TITLE
Build problem MacOS

### ISSUE THREAD

**Issue by GDelimpa** [dreal/dreal4#129]
MacOS version: 10.14.4
Bazel version: 0.24.1
Compiler: Apple LLVM version 10.0.1 (clang-1001.0.46.3)

I get the following error when running bazel build //...

> tud1000807:dreal4 gdelimpaltadak$ bazel build //...
Starting local Bazel server and connecting to it...
ERROR: /Users/gdelimpaltadak/dreal4/test/BUILD.bazel:20:1: no such package '@ibex//': Unable to complete pkg-config setup for @ibex repository: error 1 from [/usr/local/bin/pkg-config, "ibex"]:  and referenced by '//test:ibex_test'
ERROR: Analysis of target '//test:ibex_test' failed; build aborted: no such package '@ibex//': Unable to complete pkg-config setup for @ibex repository: error 1 from [/usr/local/bin/pkg-config, "ibex"]: 
INFO: Elapsed time: 4.798s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (40 packages loaded, 158 targets configured)
    Fetching @ibex; fetching

**Comment by soonho-tri** [comment]
What do you have when you run `brew list | grep "ibex"`?

**Comment by soonho-tri** [comment]
Please make sure you do `brew install dreal --only-dependencies`. You might need to do `bazel clean --expunge` before retrying `bazel build //...`.

**Comment by GDelimpa** [comment]
> What do you have when you run `brew list | grep "ibex"`?

ibex@2.6.5

> Please make sure you do brew install dreal --only-dependencies. You might need to do bazel clean --expunge before retrying bazel build //....

I will run the command and as soon as it finishes, I will notify you. At the moment it is just reinstalling gcc.

**Comment by GDelimpa** [comment]
Running the `brew install dreal --only-dependencies` command, gives me the following error:

`tud1000807:~ gdelimpaltadak$ brew install dreal --only-dependencies
==> Installing dreal from dreal/dreal
==> Installing dependencies for dreal/dreal/dreal: gcc, coinutils, readline, dreal-deps/coinor/clp, dreal-deps/ibex/ibex@2.7.4, openblas, gdbm, openssl, sqlite, python, sphinx-doc, python@2 and numpy
==> Installing dreal/dreal/dreal dependency: gcc
Warning: Building gcc from source:
  The bottle needs the Xcode CLT to be installed.
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-8.3.0/gcc-8.3.0.tar.xz
Already downloaded: /Users/gdelimpaltadak/Library/Caches/Homebrew/downloads/790ecda70af93e36763edcb183a8d4e91e433bee9bad9a60360addae9d8e82be--gcc-8.3.0.tar.xz
==> ../configure --build=x86_64-apple-darwin18.5.0 --prefix=/usr/local/Cellar/gcc/8.3.0 --libdir=/usr/
==> make BOOT_LDFLAGS=-Wl,-headerpad_max_install_names
Last 15 lines from /Users/gdelimpaltadak/Library/Logs/Homebrew/gcc/02.make:
/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/./prev-gcc/xg++ -B/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/./prev-gcc/ -B/usr/local/Cellar/gcc/8.3.0/x86_64-apple-darwin18.5.0/bin/ -nostdinc++ -B/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/src/.libs -B/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/libsupc++/.libs  -I/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/include/x86_64-apple-darwin18.5.0  -I/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/include  -I/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/libstdc++-v3/libsupc++ -L/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/src/.libs -L/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/libsupc++/.libs -fno-PIE -c  -DSTANDARD_STARTFILE_PREFIX=\"../../../\" -DSTANDARD_EXEC_PREFIX=\"/usr/local/Cellar/gcc/8.3.0/lib/gcc/8/gcc/\" -DSTANDARD_LIBEXEC_PREFIX=\"/usr/local/Cellar/gcc/8.3.0/libexec/gcc/\" -DDEFAULT_TARGET_VERSION=\"8.3.0\" -DDEFAULT_REAL_TARGET_MACHINE=\"x86_64-apple-darwin18.5.0\" -DDEFAULT_TARGET_MACHINE=\"x86_64-apple-darwin18.5.0\" -DSTANDARD_BINDIR_PREFIX=\"/usr/local/Cellar/gcc/8.3.0/bin/\" -DTOOLDIR_BASE_PREFIX=\"../../../../../../\" -DACCEL_DIR_SUFFIX=\"\" -DTARGET_SYSTEM_ROOT=\"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk\"  -DENABLE_SHARED_LIBGCC -DCONFIGURE_SPECS="\"\"" -DIN_GCC_FRONTEND -g -O2   -gtoggle -DIN_GCC     -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -I. -Ic -I../../gcc -I../../gcc/c -I../../gcc/../include -I../../gcc/../libcpp/include -I/usr/local/opt/gmp/include -I/usr/local/opt/mpfr/include -I/usr/local/opt/libmpc/include  -I../../gcc/../libdecnumber -I../../gcc/../libdecnumber/dpd -I../libdecnumber -I../../gcc/../libbacktrace -I/usr/local/opt/isl/include  -o c/gccspec.o -MT c/gccspec.o -MMD -MP -MF c/.deps/gccspec.TPo ../../gcc/c/gccspec.c
/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/./prev-gcc/xg++ -B/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/./prev-gcc/ -B/usr/local/Cellar/gcc/8.3.0/x86_64-apple-darwin18.5.0/bin/ -nostdinc++ -B/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/src/.libs -B/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/libsupc++/.libs  -I/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/include/x86_64-apple-darwin18.5.0  -I/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/include  -I/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/libstdc++-v3/libsupc++ -L/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/src/.libs -L/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/libsupc++/.libs -fno-PIE -c   -g -O2   -gtoggle -DIN_GCC     -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -I. -I. -I../../gcc -I../../gcc/. -I../../gcc/../include -I../../gcc/../libcpp/include -I/usr/local/opt/gmp/include -I/usr/local/opt/mpfr/include -I/usr/local/opt/libmpc/include  -I../../gcc/../libdecnumber -I../../gcc/../libdecnumber/dpd -I../libdecnumber -I../../gcc/../libbacktrace -I/usr/local/opt/isl/include  -o driver-i386.o -MT driver-i386.o -MMD -MP -MF ./.deps/driver-i386.TPo ../../gcc/config/i386/driver-i386.c
/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/./prev-gcc/xg++ -B/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/./prev-gcc/ -B/usr/local/Cellar/gcc/8.3.0/x86_64-apple-darwin18.5.0/bin/ -nostdinc++ -B/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/src/.libs -B/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/libsupc++/.libs  -I/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/include/x86_64-apple-darwin18.5.0  -I/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/include  -I/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/libstdc++-v3/libsupc++ -L/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/src/.libs -L/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/libsupc++/.libs -fno-PIE -c   -g -O2   -gtoggle -DIN_GCC     -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -I. -I. -I../../gcc -I../../gcc/. -I../../gcc/../include -I../../gcc/../libcpp/include -I/usr/local/opt/gmp/include -I/usr/local/opt/mpfr/include -I/usr/local/opt/libmpc/include  -I../../gcc/../libdecnumber -I../../gcc/../libdecnumber/dpd -I../libdecnumber -I../../gcc/../libbacktrace -I/usr/local/opt/isl/include  -o darwin-driver.o -MT darwin-driver.o -MMD -MP -MF ./.deps/darwin-driver.TPo ../../gcc/config/darwin-driver.c
/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/./prev-gcc/xg++ -B/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/./prev-gcc/ -B/usr/local/Cellar/gcc/8.3.0/x86_64-apple-darwin18.5.0/bin/ -nostdinc++ -B/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/src/.libs -B/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/libsupc++/.libs  -I/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/include/x86_64-apple-darwin18.5.0  -I/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/include  -I/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/libstdc++-v3/libsupc++ -L/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/src/.libs -L/private/tmp/gcc-20190404-9376-1odghdo/gcc-8.3.0/build/prev-x86_64-apple-darwin18.5.0/libstdc++-v3/libsupc++/.libs -fno-PIE -c   -g -O2   -gtoggle -DIN_GCC     -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -I. -Ic-family -I../../gcc -I../../gcc/c-family -I../../gcc/../include -I../../gcc/../libcpp/include -I/usr/local/opt/gmp/include -I/usr/local/opt/mpfr/include -I/usr/local/opt/libmpc/include  -I../../gcc/../libdecnumber -I../../gcc/../libdecnumber/dpd -I../libdecnumber -I../../gcc/../libbacktrace -I/usr/local/opt/isl/include  -o c-family/cppspec.o -MT c-family/cppspec.o -MMD -MP -MF c-family/.deps/cppspec.TPo ../../gcc/c-family/cppspec.c
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/sysctl.h:83,
                 from ../../gcc/config/darwin-driver.c:30:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/ucred.h:94:2: error: '_Atomic' does not name a type
  _Atomic u_long          cr_ref;  /* reference count */
  ^~~~~~~
make[3]: *** [darwin-driver.o] Error 1
make[3]: *** Waiting for unfinished jobs....
rm gcc.pod gfortran.pod
make[2]: *** [all-stage2-gcc] Error 2
make[1]: *** [stage2-bubble] Error 2
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

`

**Comment by soonho-tri** [comment]
I don't think this is a dreal issue.
```
Warning: Building gcc from source:
The bottle needs the Xcode CLT to be installed.
```
Can you install XCode command line tool and retry? Also as a general homebrew tip, run `brew doctor` and see if it suggests reasonable fixes.

**Comment by soonho-tri** [comment]
Also FYI, we've switched to using `ibex@2.7.4`. As long as you can do `brew install dreal-deps/ibex/ibex@2.7.4`, the ibex problem should go away.

**Comment by GDelimpa** [comment]
> Also FYI, we've switched to use `ibex@2.7.4`. As long as you can do `brew install dreal-deps/ibex/ibex@2.7.4`, the ibex problem should go away.

I think it fixed the problem! Thanks Soonho!

**Comment by soonho-tri** [comment]
Great!
