### ISSUE TITLE
macOS pip issue 

### ISSUE THREAD

**Issue by JohnMesserly** [dreal/dreal4#130]
I can build dreal with bazel. I've updated ibex to 2.7.4. as in the adjacent macOS issues, and installed dependencies (including hidden bison and flex). However, I cannot use pip install dreal or pip3 install dreal. I get the following error. The actual output is confusing, but somewhere it says I need to "build in a workspace". Google tells me that I need to have an empty WORKSPACE file (i.e. touch WORKSPACE), but this does not help :( 

```
Collecting dreal
  Using cached https://files.pythonhosted.org/packages/c8/b3/1cc03ce34ee76334c50eb02d34007557cb41a8c4adb24083b5abaa18d62b/dreal-4.19.4.1.tar.gz
Building wheels for collected packages: dreal
  Building wheel for dreal (setup.py) ... error
  Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/ry/mqpmtfg52kg5ms31nr7993x40000gn/T/pip-install-d1_zg4j2/dreal/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/ry/mqpmtfg52kg5ms31nr7993x40000gn/T/pip-wheel-2s9vvqqf --python-tag cp36:
  /Users/johnmesserly/.local/lib/python3.6/site-packages/setuptools/dist.py:475: UserWarning: Normalizing '4.19.04.1' to '4.19.4.1'
    normalized_version,
  running bdist_wheel
  running build
  Building dReal
  ERROR: The 'build' command is only supported from within a workspace.
  WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
  error: Unable to build dReal.
  
  ----------------------------------------
  Failed building wheel for dreal
  Running setup.py clean for dreal
Failed to build dreal
Installing collected packages: dreal
  Running setup.py install for dreal ... error
    Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/ry/mqpmtfg52kg5ms31nr7993x40000gn/T/pip-install-d1_zg4j2/dreal/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/ry/mqpmtfg52kg5ms31nr7993x40000gn/T/pip-record-tmk3559a/install-record.txt --single-version-externally-managed --compile:
    /Users/johnmesserly/.local/lib/python3.6/site-packages/setuptools/dist.py:475: UserWarning: Normalizing '4.19.04.1' to '4.19.4.1'
      normalized_version,
    running install
    running build
    Building dReal
    ERROR: The 'build' command is only supported from within a workspace.
    WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
    error: Unable to build dReal.
    
    ----------------------------------------
Command "/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/ry/mqpmtfg52kg5ms31nr7993x40000gn/T/pip-install-d1_zg4j2/dreal/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/ry/mqpmtfg52kg5ms31nr7993x40000gn/T/pip-record-tmk3559a/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/ry/mqpmtfg52kg5ms31nr7993x40000gn/T/pip-install-d1_zg4j2/dreal/
```

**Comment by soonho-tri** [comment]
Hi @JohnMesserly ,

Thanks for the report. For now, `build from source` is not a supported method. I'll fix it soon.

On macOS, we only provide a pre-built library for `python3.7` while it seems that you're using `python3.6` via `anaconda3`. While I'm fixing the issue, can you switch to `python3.7` and try `pip` again?

**Comment by soonho-tri** [comment]
@JohnMesserly , I've released `4.19.4.2`. Can you try `pip3 install dreal --upgrade`?

**Comment by JohnMesserly** [comment]
i tried pip3.7 and it both installs and works fine, so essentially I am able to work with dreal now and the issue can for the most part be closed. thanks :) 

however, i just ran the pip3 install dreal --upgrade, and it installs correctly but gives me import errors when trying to run on a python file (this python file only has the single line "import dreal" in it)

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import dreal
  File "/anaconda3/lib/python3.6/site-packages/dreal/__init__.py", line 7, in <module>
    from dreal._dreal_py import *
ImportError: dlopen(/anaconda3/lib/python3.6/site-packages/dreal/_dreal_py.so, 2): Symbol not found: _PyThread_tss_alloc
  Referenced from: /anaconda3/lib/python3.6/site-packages/dreal/_dreal_py.so
  Expected in: flat namespace
 in /anaconda3/lib/python3.6/site-packages/dreal/_dreal_py.so

**Comment by soonho-tri** [comment]
Thanks for the test. I think there is another problem. When dReal is being compiled, it uses the python3 provided by the homebrew-python (which is `3.7`) while it should have used the one provided by anaconda (`3.6` in your case). This version mismatch causes the problem.

I'll try to fix the issue on my side. But I think it could take some time.

**Comment by soonho-tri** [comment]
@JohnMesserly , I think I've fixed the problem. Can you test `pip install --index-url https://test.pypi.org/simple dreal --user` when you have some time? It should pick up `4.19.4.3.1`.

**Comment by JohnMesserly** [comment]
I'm getting a "requirement already satisfied", i.e. it's still pulling 4.19.4.2 

also, i saw theres decent documentation for c++ but I can't seem to find any documentation / users manual with python. if i want to use python, is the best thing to do learn the c++ and then look into dreal_py.cc?

**Comment by soonho-tri** [comment]
I guess you need to add `--upgrade` at the end of `pip`, or need to uninstall `dreal` first before you run `pip`.

**Comment by soonho-tri** [comment]
Regarding Python documentation, for now, it's best to read the unittests in [dreal/test/python](https://github.com/dreal/dreal4/blob/master/dreal/test/python) directory, such as [symbolic_test.py](https://github.com/dreal/dreal4/blob/master/dreal/test/python/symbolic_test.py).

**Comment by soonho-tri** [comment]
I've tested it locally using `virtualenv` and `pyenv`. I'm closing this issue for now. Please feel free to re-open it if you find an issue.

**Comment by ParivashFeyzishendi** [comment]
Hi,
I tried to install dreal but doesn't work!

error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/zw/f1q4ydk97ds1c1kvy23j3fkr0000gn/T/pip-install-hwklyv0q/dreal_ac9bc264057247bc9d8ea7dd2324867d/setup.py", line 144, in <module>
          import wheel.pep425tags
      ModuleNotFoundError: No module named 'wheel.pep425tags'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dreal
  Running setup.py clean for dreal
Failed to build dreal
Installing collected packages: dreal
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  Running setup.py install for dreal ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for dreal did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      /opt/homebrew/lib/python3.9/site-packages/setuptools/config/setupcfg.py:459: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running install
      /opt/homebrew/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      Building dReal
      Starting local Bazel server and connecting to it...
      Loading:
      Loading: 0 packages loaded
      Analyzing: 2 targets (2 packages loaded, 0 targets configured)
      ERROR: /private/var/folders/zw/f1q4ydk97ds1c1kvy23j3fkr0000gn/T/pip-install-hwklyv0q/dreal_ac9bc264057247bc9d8ea7dd2324867d/third_party/com_github_google_kythe/tools/build_rules/lexyacc.bzl:27:64: invalid escape sequence: \.. Use '\\' to insert '\'.
      ERROR: /private/var/folders/zw/f1q4ydk97ds1c1kvy23j3fkr0000gn/T/pip-install-hwklyv0q/dreal_ac9bc264057247bc9d8ea7dd2324867d/dreal/BUILD.bazel:58:21: While resolving toolchains for target //dreal:_dreal_py.so: invalid registered toolchain '@dreal//third_party/com_github_google_kythe/tools/build_rules:lexyacc_remote_toolchain': error loading package 'third_party/com_github_google_kythe/tools/build_rules': compilation of module 'third_party/com_github_google_kythe/tools/build_rules/lexyacc.bzl' failed
      ERROR: Analysis of target '//dreal:_dreal_py.so' failed; build aborted:
      INFO: Elapsed time: 1.642s
      INFO: 0 processes.
      FAILED: Build did NOT complete successfully (21 packages loaded, 7 targets configured)
      FAILED: Build did NOT complete successfully (21 packages loaded, 7 targets configured)
      error: Unable to build dReal.
      Please visit https://pypi.org/project/dreal and follow the instructions to install the prerequsites.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dreal

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
parivashfeyzishendi@Parivashs-MacBook-Air ~ % pip3 install dreal --upgrade
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting dreal
  Using cached dreal-4.20.4.1.tar.gz (266 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: dreal
  Building wheel for dreal (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/zw/f1q4ydk97ds1c1kvy23j3fkr0000gn/T/pip-install-o2n86ucc/dreal_51bf5c7ca96e4905beed353e419ed530/setup.py", line 144, in <module>
          import wheel.pep425tags
      ModuleNotFoundError: No module named 'wheel.pep425tags'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dreal
  Running setup.py clean for dreal
Failed to build dreal
Installing collected packages: dreal
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  Running setup.py install for dreal ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for dreal did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      /opt/homebrew/lib/python3.9/site-packages/setuptools/config/setupcfg.py:459: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running install
      /opt/homebrew/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      Building dReal
      Starting local Bazel server and connecting to it...
      Loading:
      Loading: 0 packages loaded
      Analyzing: 2 targets (2 packages loaded, 0 targets configured)
      ERROR: /private/var/folders/zw/f1q4ydk97ds1c1kvy23j3fkr0000gn/T/pip-install-o2n86ucc/dreal_51bf5c7ca96e4905beed353e419ed530/third_party/com_github_google_kythe/tools/build_rules/lexyacc.bzl:27:64: invalid escape sequence: \.. Use '\\' to insert '\'.
      ERROR: /private/var/folders/zw/f1q4ydk97ds1c1kvy23j3fkr0000gn/T/pip-install-o2n86ucc/dreal_51bf5c7ca96e4905beed353e419ed530/dreal/BUILD.bazel:58:21: While resolving toolchains for target //dreal:_dreal_py.so: invalid registered toolchain '@dreal//third_party/com_github_google_kythe/tools/build_rules:lexyacc_remote_toolchain': error loading package 'third_party/com_github_google_kythe/tools/build_rules': compilation of module 'third_party/com_github_google_kythe/tools/build_rules/lexyacc.bzl' failed
      ERROR: Analysis of target '//dreal:_dreal_py.so' failed; build aborted:
      INFO: Elapsed time: 1.469s
      INFO: 0 processes.
      FAILED: Build did NOT complete successfully (23 packages loaded, 7 targets configured)
      FAILED: Build did NOT complete successfully (23 packages loaded, 7 targets configured)
      error: Unable to build dReal.
      Please visit https://pypi.org/project/dreal and follow the instructions to install the prerequsites.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dreal

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
parivashfeyzishendi@Parivashs-MacBook-Air ~ % pip install --index-url https://test.pypi.org/simple dreal --user
Looking in indexes: https://test.pypi.org/simple
Collecting dreal
  Downloading https://test-files.pythonhosted.org/packages/dd/37/bf27310eb3efd0582d79f26fae2102819639561200f379a1ba2606c46cc4/dreal-4.19.4.3.1.tar.gz (231 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.7/231.7 kB 2.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: dreal
  Building wheel for dreal (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/zw/f1q4ydk97ds1c1kvy23j3fkr0000gn/T/pip-install-uubv19j_/dreal_015c2d1dd85a4178b9b2c8e2b45a2016/setup.py", line 118, in <module>
          import wheel.pep425tags
      ModuleNotFoundError: No module named 'wheel.pep425tags'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dreal
  Running setup.py clean for dreal
Failed to build dreal
Installing collected packages: dreal
  Running setup.py install for dreal ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for dreal did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running install
      running build
      Building dReal
      Starting local Bazel server and connecting to it...
      Loading:
      Loading: 0 packages loaded
      ERROR: Traceback (most recent call last):
          File "/private/var/folders/zw/f1q4ydk97ds1c1kvy23j3fkr0000gn/T/pip-install-uubv19j_/dreal_015c2d1dd85a4178b9b2c8e2b45a2016/BUILD.bazel", line 10, column 53, in <toplevel>
                  load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_deb", "pkg_tar")
      Error: file '@bazel_tools//tools/build_defs/pkg:pkg.bzl' does not contain symbol 'pkg_deb' (did you mean 'pkg_tar'?)
      ERROR: Skipping '//:libdreal.so': no such target '//:libdreal.so': target 'libdreal.so' not declared in package '' defined by /private/var/folders/zw/f1q4ydk97ds1c1kvy23j3fkr0000gn/T/pip-install-uubv19j_/dreal_015c2d1dd85a4178b9b2c8e2b45a2016/BUILD.bazel
      ERROR: no such target '//:libdreal.so': target 'libdreal.so' not declared in package '' defined by /private/var/folders/zw/f1q4ydk97ds1c1kvy23j3fkr0000gn/T/pip-install-uubv19j_/dreal_015c2d1dd85a4178b9b2c8e2b45a2016/BUILD.bazel
      INFO: Elapsed time: 1.550s
      INFO: 0 processes.
      FAILED: Build did NOT complete successfully (2 packages loaded)
      FAILED: Build did NOT complete successfully (2 packages loaded)
      error: Unable to build dReal.
      Please visit https://pypi.org/project/dreal and follow the instructions to install the prerequsites.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dreal

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
parivashfeyzishendi@Parivashs-MacBook-Air ~ % pip install dreal --upgrade
Collecting dreal
  Using cached dreal-4.20.4.1.tar.gz (266 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: dreal
  Building wheel for dreal (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/zw/f1q4ydk97ds1c1kvy23j3fkr0000gn/T/pip-install-ah1tocyw/dreal_59d82f14f770451f9054040a4de57412/setup.py", line 144, in <module>
          import wheel.pep425tags
      ModuleNotFoundError: No module named 'wheel.pep425tags'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dreal
  Running setup.py clean for dreal
Failed to build dreal
Installing collected packages: dreal
  Running setup.py install for dreal ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for dreal did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      running install
      running build
      Building dReal
      Starting local Bazel server and connecting to it...
      Loading:
      Loading: 0 packages loaded
      Analyzing: 2 targets (2 packages loaded, 0 targets configured)
      ERROR: /private/var/folders/zw/f1q4ydk97ds1c1kvy23j3fkr0000gn/T/pip-install-ah1tocyw/dreal_59d82f14f770451f9054040a4de57412/third_party/com_github_google_kythe/tools/build_rules/lexyacc.bzl:27:64: invalid escape sequence: \.. Use '\\' to insert '\'.
      ERROR: /private/var/folders/zw/f1q4ydk97ds1c1kvy23j3fkr0000gn/T/pip-install-ah1tocyw/dreal_59d82f14f770451f9054040a4de57412/BUILD.bazel:23:10: While resolving toolchains for target //:libdreal.so: invalid registered toolchain '@dreal//third_party/com_github_google_kythe/tools/build_rules:lexyacc_remote_toolchain': error loading package 'third_party/com_github_google_kythe/tools/build_rules': compilation of module 'third_party/com_github_google_kythe/tools/build_rules/lexyacc.bzl' failed
      ERROR: Analysis of target '//:libdreal.so' failed; build aborted:
      INFO: Elapsed time: 1.453s
      INFO: 0 processes.
      FAILED: Build did NOT complete successfully (12 packages loaded, 7 targets configured)
      FAILED: Build did NOT complete successfully (12 packages loaded, 7 targets configured)
      error: Unable to build dReal.
      Please visit https://pypi.org/project/dreal and follow the instructions to install the prerequsites.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dreal

**Comment by soonhokong** [comment]
Can you confirm that you're using a M1/M2 mac? We do not support the platform yet.

**Comment by ParivashFeyzishendi** [comment]
Yes, I'm using M1 mac.

**Comment by dibrinsofor** [comment]
Any chance you now support apple silicon?

**Comment by soonhokong** [comment]
@dibrinsofor , not yet. But I'm working on it.
