### ISSUE TITLE
dreal4/setup/ubuntu/14.04/ is missing install.sh

### ISSUE THREAD

**Issue by dddejan** [dreal/dreal4#138]
To be consistent/uniform with 16.04 and 18.04.

The idea is that I could install with `curl .../$(lsb_release -rs)/install.sh`

**Comment by soonho-tri** [comment]
Hi Dejan, Ubuntu 14.04 reached its end of standard support on April 30, 2019 and we do not want to support it any longer. FYI, you can find the old files at https://github.com/dreal/dreal4/tree/4.18.03.3/setup/ubuntu/14.04.

**Comment by dddejan** [comment]
OK, good to know. It's still the default image on travis so things fail.

**Comment by soonho-tri** [comment]
FWIW, you can add “dist: xenial” in your setup to enforce 16.04.

**Comment by dddejan** [comment]
Or switch to circleci, travis is becoming a headache ;)
