### ISSUE TITLE
Exposing spdlog::level::info in the Python API

### ISSUE THREAD

**Issue by jonathan-laurent** [dreal/dreal4#140]
The command line interface of dReal allows for the following verbosity levels: `trace, debug, info, warning, error, critical, off`. However, "info" is missing from the Python API:

https://github.com/dreal/dreal4/blob/799ef73a7793c7b6561ab382f7a0244e8d875cb4/dreal/dreal_py.cc#L731-L738

**Comment by soonho-tri** [comment]
Thanks for the report. Fixed by 6dc7389d0d817194d5c954ac59227fbf4a20ec52.
