### ISSUE TITLE
Exposing "let" constructs in the python API

### ISSUE THREAD

**Issue by jonathan-laurent** [dreal/dreal4#142]
Would-it be possible to expose the `let` construct from SMTLIB in the Python API?
This would enable declaring shared sub-expressions explicitly without introducing additional variables.

**Comment by soonho-tri** [comment]
FYI, we do not have `let` internally in dReal. In SMT2 parsing, it is de-sugared by adding an additional variable anyway.

**Comment by scungao** [comment]
With API you can do whatever you want with the expressions before sending them to the final satisfiability check anyway right? For example https://gist.github.com/scungao/4b90c34f29de2f457d4e79c5335bf04d

**Comment by jonathan-laurent** [comment]
@scungao I agree that you can use the API to combine expressions before sending them to dReal. However, without an explicit mechanism to enforce sharing, I am afraid that some sub-expressions may be evaluated more times than necessary during pruning. In some applications where sharing is pervasive (e.g. evaluation of a deep neural network), this would result in an exponential blow-up.

For example, the following code:
```python
x = Variable("x")
y = f(x)
z = g(y, y+1)
CheckSatisfiability(z > 0)
```
is equivalent to
```python
x = Variable("x")
CheckSatisfiability(g(f(x), f(x) + 1) > 0)
```
Here, would dReal perform any kind of optimization to ensure that `f(Ix)` isn't computed twice during interval propagation?

**Comment by scungao** [comment]
those subexpressions are shared, won't have duplicated computation there

**Comment by jonathan-laurent** [comment]
Great, thanks!
