### ISSUE TITLE
about the encoding of ode/integration 

### ISSUE THREAD

**Issue by huangl223** [dreal/dreal4#144]
When I type the following code  in dreal:
**(set-logic QF_NRA)
(declare-fun x () Real)
(declare-fun y () Real)
(declare-fun x_1 () Real)
(declare-fun x_0 () Real)
(declare-fun y_1 () Real)
(declare-fun y_0 () Real)
(declare-fun time_0 () Real)
(define-ode flow ((= d/dt[x] 1) (= d/dt[y] 1)))
(assert (= [x_1 y_1] (integral 0. time_0 [x_0 y_0] flow)))
(check-sat)
(exit)**

it gives :
**terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted (core dumped)**

is there any syntax error in the encodings?

**Comment by soonho-tri** [comment]
which version of dReal are you using?

**Comment by scungao** [comment]
Please use dReal3 for ODE solving; it's not implemented in dReal4 yet.

**Comment by huangl223** [comment]
> Please use dReal3 for ODE solving; it's not implemented in dReal4 yet.
yes, it works in dreal v3.0! Thanks!
