### ISSUE TITLE
Variable is missing from dreal.symbolic

### ISSUE THREAD

**Issue by vstadnytskyi** [dreal/dreal4#145]
I have an import issue with dreal, see below. I am not sure what to do with that.

```
femto13:microfluidics femto-13$ ipython3
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24)

Type 'copyright', 'credits' or 'license' for more information
IPython 7.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pymanifold
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-2bb352dc2fb6> in <module>
----> 1 import pymanifold

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymanifold/__init__.py in <module>
----> 1 from pymanifold.pymanifold import Schematic

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pymanifold/pymanifold.py in <module>
      7 #  from build.lib.data.dreal.symbolic import Variable, logical_and, sin, cos
      8 #  from build.lib.data.dreal.api import CheckSatisfiability, Minimize
----> 9 from dreal.symbolic import Variable, logical_and, sin, cos
     10 from dreal.api import CheckSatisfiability, Minimize
     11 #  from pysmt.typing import REAL

ImportError: cannot import name 'Variable' from 'dreal.symbolic' (unknown location)
```

**Comment by soonho-tri** [comment]
Can you test `from dreal import Variable` instead of `from dreal.symbolic import Variable`?

**Comment by vstadnytskyi** [comment]
Yes, I can import Variable from dreal

In [7]: from dreal import Variable

In [8]: Variable.__dict__
Out[8]:
mappingproxy({'__init__': <instancemethod __init__ at 0x1119faeb8>,
              '__doc__': None,
              '__module__': 'dreal._dreal_py',
              'get_id': <instancemethod get_id at 0x1119faee8>,
              'get_type': <instancemethod get_type at 0x1119faf48>,

              '__str__': <instancemethod __str__ at 0x1119fafa8>,
              '__repr__': <instancemethod __repr__ at 0x1119f7048>,
              '__hash__': <instancemethod __hash__ at 0x1119f70a8>,
              '__add__': <instancemethod __add__ at 0x1119f7138>,
              '__radd__': <instancemethod __radd__ at 0x1119f7168>,
              '__sub__': <instancemethod __sub__ at 0x1119f71f8>,
              '__rsub__': <instancemethod __rsub__ at 0x1119f7228>,
              '__mul__': <instancemethod __mul__ at 0x1119f72b8>,
              '__rmul__': <instancemethod __rmul__ at 0x1119f72e8>,
              '__truediv__': <instancemethod __truediv__ at 0x1119f7378>,
              '__rtruediv__': <instancemethod __rtruediv__ at 0x1119f73a8>,
              '__pow__': <instancemethod __pow__ at 0x1119f7408>,
              '__pos__': <instancemethod __pos__ at 0x1119f7468>,
              '__neg__': <instancemethod __neg__ at 0x1119f74c8>,
              '__lt__': <instancemethod __lt__ at 0x1119f7528>,
              '__le__': <instancemethod __le__ at 0x1119f7588>,
              '__gt__': <instancemethod __gt__ at 0x1119f75e8>,
              '__ge__': <instancemethod __ge__ at 0x1119f7648>,
              '__eq__': <instancemethod __eq__ at 0x1119f76a8>,
              '__ne__': <instancemethod __ne__ at 0x1119f7708>,
              'Type': dreal._dreal_py.Variable.Type,
              'Real': Type.Real,
              'Int': Type.Int,
              'Bool': Type.Bool,
              'Binary': Type.Binary})

**Comment by soonho-tri** [comment]
Reading the messages, I don't understand the problem. I guess pymanifold is based on an old version of dReal's python binding and you have this issue. If so, I think you can talk to its maintainer and hopefully find a solution.
