### ISSUE TITLE
Definefun Feature

### ISSUE THREAD

**Issue by auroraschmidt** [dreal/dreal4#147]
Dear dreal creators, 

We are really interested in using this software in a verification project but are finding it challenging not having a "define fun" sort of capability. Is this a feature that might appear sometime or is there workaround you could point us to?

Thanks!

**Comment by soonho-tri** [comment]
For now, we do not support `define-fun` in SMT2 parsing, which is on my todo list.

I guess you're using dReal via its SMT2 interface. Have you considering using its Python binding? You can define a python function that takes in symbolic expressions and returns a symbolic expression. Then you can use this function to form a complex symbolic expression. Here is a small example.

```python
from dreal import *

x = Variable("x")
y = Variable("y")
z = Variable("z")

def my_func(p1, p2):
  return sin(p1) + cos(p2)

f_sat = And(0 <= x, x <= 10,
            0 <= y, y <= 10,
            0 <= z, z <= 10,
            my_func(x, y) == z)

print(f_sat)

result = CheckSatisfiability(f_sat, 0.001)
print(result)
```

Output:
```
(((sin(x) + cos(y)) == z) and (x >= 0) and (y >= 0) and (z >= 0) and (x <= 10) and (y <= 10) and (z <= 10))
x : [1.247234518484574339, 1.247580203674002686]
y : [8.929064928123818135, 8.929756298502674383]
z : [0.06815055407334302817, 0.06858905276351445757]
```

To learn more about the Python binding, please check https://github.com/dreal/dreal4#python-binding. You can also find more examples at https://github.com/dreal/dreal4/tree/master/dreal/test/python

**Comment by auroraschmidt** [comment]
Thank you so much! This does address what we were looking for!

**Comment by soonho-tri** [comment]
Good to know! Closing the issue then.
