### ISSUE TITLE
Links need updating.

### ISSUE THREAD

**Issue by ianamason** [dreal/dreal4#151]
Many of the links on [this](http://dreal.github.io/) page are broken or out of date.

These all 404:

172.smt.verbose
172.smt2.proof
172.smt2.proof.output
and 
172.smt2.proof.extra

The opensmt link needs to be updated.

**Comment by soonho-tri** [comment]
FYI, the webpage is based on the previous version, dReal3, and mostly out of date. We have a plan to make a new webpage but no timeline yet.

**Comment by ianamason** [comment]
Good, may I suggest that you add a sketch of the current architecture? You
no longer use realparver, is that correct?

While I have your attention, it would be nice to have a `--version` command line option.

**Comment by soonho-tri** [comment]
Correct, it does not use realpaver. You can find its core dependencies at https://github.com/dreal/dreal4/blob/master/dreal/workspace.bzl.

> While I have your attention, it would be nice to have a --version command line option.

Sure. Will do it soon.

**Comment by soonho-tri** [comment]
> While I have your attention, it would be nice to have a --version command line option.

Done by https://github.com/dreal/dreal4/commit/9181114df2f22a0168232e1e8bf2e183f62c8988

> FYI, the webpage is based on the previous version, dReal3, and mostly out of date. We have a plan to make a new webpage but no timeline yet.

Feel free to subscribe to https://github.com/dreal/dreal4/issues/153.
