### ISSUE TITLE
How to "dReal --proof xxx.smt" with v4?

### ISSUE THREAD

**Issue by zeta1999** [dreal/dreal4#155]
(aside from that, a super cool project as far as I am concerned)

I am especially interested in having the option to check unsat results independently (say, for analytical results a la Cauchy-Schwartz to validate some numerical algorithms - as a an initial phase before going the "Gappa" way for IEEE aware proofs)

**Comment by scungao** [comment]
Adding --proof in v4 is pretty close to the bottom in our stack right now. Try the v3 support for it first?

**Comment by soonho-tri** [comment]
IIRC, this feature is only available in [dReal2](https://github.com/dreal/dreal2). We will update our webpage not to confuse users to think that this feature is available in the current version.

**Comment by zeta1999** [comment]
Thanks for the precision ;-)

**Comment by DustinWehr** [comment]
Is there enough information in the `--verbosity debug` log to construct a proof for conjunctions of real arithmetic inequalities?

v3 has the --proof option, but even with no options the latest linux binary seg faults on my machine.
