### ISSUE TITLE
Denoting the latest release

### ISSUE THREAD

**Issue by jwnimmer-tri** [dreal/dreal4#161]
If I call the GitHub API `github3.login(...).repository("dreal", "dreal4").latest_release().tag_name`, I get `cav19` instead of `4.19.10.3`.

Is it easy to tweak your release process so that the latest release API returns the newest one?  If not, perhaps I could add work-around to my https://github.com/RobotLocomotion/drake/blob/eef03571ad1517157d1ac24d692a7349d4ab8a2a/tools/workspace/new_release.py to identify repositories with tags-but-not-releases and then do my own semver logic atop that (to eschew dotless tags).

**Comment by jwnimmer-tri** [comment]
Oops, my apologies -- my code is not using the `latest_release()` branch like I thought it was.  I can fix the alpha-sorting of tags on my end.

**Comment by soonho-tri** [comment]
Anyway, I've just released a new one. So far I have just tagged commits. Could you check again?

**Comment by jwnimmer-tri** [comment]
Yes, the `latest_release` attribute works properly now.
