### ISSUE TITLE
problem with implies

### ISSUE THREAD

**Issue by amaleki2** [dreal/dreal4#163]
if I run this
```
z = Variable("z")
V = z**2 + 4
cond1 = And(0 <= z, z <= 10)
cond2 = Implies(cond1, V >= 0.001)
result = CheckSatisfiability(cond2, 0.001)
print(result)
```
The result I get is `z : [1.797693134862315708e+308, 1.797693134862315708e+308]`
And if I change `V = z**2 - 4` I get the same.
why is that?

**Comment by soonho-tri** [comment]
`cond1 -> cond2` is true if `cond1` is `false`. With the assignment `z : [1.797693134862315708e+308, 1.797693134862315708e+308]`, `cond1` is evaluated to `false`.

**Comment by amaleki2** [comment]
that makes sense. thanks,
