### ISSUE TITLE
coin-clp solver

### ISSUE THREAD

**Issue by dathath** [dreal/dreal4#165]
dreal is unable to find the dependencies (particularly the coin-clp solver binary). When I try to import dreal from inside python I get the follow error message:

--------------------------------------------------------

ImportError: libClpSolver.so.1: cannot open shared object file: No such file or directory

Could you please help me with this?

Thanks! I installed prereqs from the ./install_prereqs.sh script, and I am running ubuntu 16.04.

**Comment by soonho-tri** [comment]
1) Which python version that you're using?
2) Can you install and run dReal binary (command-line program) without an error?

**Comment by dathath** [comment]
1. Have same issue with python 3.7 and python 3.5
2. Yes. I am able to run it from the command-line. For instance, this works as expected:

$ /opt/dreal/${DREAL_VERSION}/bin/dreal --in 172.smt 
unsat

**Comment by soonho-tri** [comment]
Can you check if `pip3 install -e git+https://github.com/dreal/dreal4#egg=dreal` works? You need to remove `dreal` using `pip3 uninstall` before running the command.

**Comment by dathath** [comment]
Yes! This worked, thanks!

**Comment by soonho-tri** [comment]
FYI, I fixed the problem in `4.19.10.3`. `pip3 install dreal` should just work now.
