### ISSUE TITLE
Installation Error: fetch of pybind11

### ISSUE THREAD

**Issue by GDelimpa** [dreal/dreal4#167]
I tried to build dreal4 in MacOS Catalina 10.15.2, but I get an error. Specifically, the first two commands
`git clone https://github.com/dreal/dreal4 && cd dreal4
./setup/mac/install_prereqs.sh`
seem to run fine, except for one warning (building gcc from source). 

However, when I run
`bazel build //...`
I get the following error:
> ERROR: An error occurred during the fetch of repository 'pybind11':
   java.io.IOException: Error downloading [https://github.com/pybind/pybind11/archive/v2.4.1.tar.gz] to /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/pybind11/v2.4.1.tar.gz: Read timed out

After that, I get a lot of subsequent errors that have to do with the previous one, and eventually the installation stops.

**Comment by soonho-tri** [comment]
I guess it's due to a network glitch. To make sure, can you try the following?

```bash
bazel clean --expunge
bazel sync
```

If they work, please try `bazel build //...`.

**Comment by GDelimpa** [comment]
The command `bazel clean --expunge` runs without problems. However `bazel sync` gives the following errors:

> Starting local Bazel server and connecting to it...
INFO: Call stack for the definition of repository 'remote_java_tools_linux' which is a http_archive (rule definition at /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:260:1
WARNING: Download from https://mirror.bazel.build/bazel_java_tools/releases/javac11/v6.1/java_tools_javac11_linux-v6.1.zip failed: class java.io.IOException java.net.SocketTimeoutException: Read timed out
WARNING: Download from https://github.com/bazelbuild/java_tools/releases/download/javac11-v6.1/java_tools_javac11_linux-v6.1.zip failed: class javax.net.ssl.SSLProtocolException Read timed out
ERROR: An error occurred during the fetch of repository 'remote_java_tools_linux':
   java.io.IOException: Error downloading [https://mirror.bazel.build/bazel_java_tools/releases/javac11/v6.1/java_tools_javac11_linux-v6.1.zip, https://github.com/bazelbuild/java_tools/releases/download/javac11-v6.1/java_tools_javac11_linux-v6.1.zip] to /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/remote_java_tools_linux/java_tools_javac11_linux-v6.1.zip: Read timed out
INFO: Call stack for the definition of repository 'remote_java_tools_windows' which is a http_archive (rule definition at /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:270:1
WARNING: Download from https://mirror.bazel.build/bazel_java_tools/releases/javac11/v6.1/java_tools_javac11_windows-v6.1.zip failed: class javax.net.ssl.SSLProtocolException Read timed out
WARNING: Download from https://github.com/bazelbuild/java_tools/releases/download/javac11-v6.1/java_tools_javac11_windows-v6.1.zip failed: class javax.net.ssl.SSLProtocolException Read timed out
ERROR: An error occurred during the fetch of repository 'remote_java_tools_windows':
   java.io.IOException: Error downloading [https://mirror.bazel.build/bazel_java_tools/releases/javac11/v6.1/java_tools_javac11_windows-v6.1.zip, https://github.com/bazelbuild/java_tools/releases/download/javac11-v6.1/java_tools_javac11_windows-v6.1.zip] to /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/remote_java_tools_windows/java_tools_javac11_windows-v6.1.zip: Read timed out
INFO: Call stack for the definition of repository 'remotejdk_linux_aarch64' which is a http_archive (rule definition at /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:155:1
WARNING: Download from https://mirror.bazel.build/openjdk.linaro.org/releases/jdk9-server-release-1708.tar.xz failed: class javax.net.ssl.SSLProtocolException Read timed out
WARNING: Download from http://openjdk.linaro.org/releases/jdk9-server-release-1708.tar.xz failed: class java.io.IOException java.net.SocketTimeoutException: Read timed out
ERROR: An error occurred during the fetch of repository 'remotejdk_linux_aarch64':
   java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk.linaro.org/releases/jdk9-server-release-1708.tar.xz, http://openjdk.linaro.org/releases/jdk9-server-release-1708.tar.xz] to /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/remotejdk_linux_aarch64/jdk9-server-release-1708.tar.xz: java.net.SocketTimeoutException: Read timed out
INFO: Call stack for the definition of repository 'remotejdk10_win' which is a http_archive (rule definition at /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:190:1
WARNING: Download from https://mirror.bazel.build/openjdk/azul-zulu10.2+3-jdk10.0.1/zulu10.2+3-jdk10.0.1-win_x64-allmodules.zip failed: class javax.net.ssl.SSLProtocolException Read timed out
ERROR: An error occurred during the fetch of repository 'remotejdk10_win':
   java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu10.2+3-jdk10.0.1/zulu10.2+3-jdk10.0.1-win_x64-allmodules.zip] to /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/remotejdk10_win/zulu10.2+3-jdk10.0.1-win_x64-allmodules.zip: Read timed out
INFO: Call stack for the definition of repository 'remotejdk10_linux_aarch64' which is a http_archive (rule definition at /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:203:1
WARNING: Download from https://mirror.bazel.build/openjdk.linaro.org/releases/jdk10-server-release-1804.tar.xz failed: class javax.net.ssl.SSLProtocolException Read timed out
ERROR: An error occurred during the fetch of repository 'remotejdk10_linux_aarch64':
   java.io.IOException: thread interrupted
INFO: Call stack for the definition of repository 'remotejdk11_linux_aarch64' which is a http_archive (rule definition at /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:227:1
WARNING: Download from https://mirror.bazel.build/openjdk/azul-zulu11.31.15-ca-jdk11.0.3/zulu11.31.15-ca-jdk11.0.3-linux_aarch64.tar.gz failed: class javax.net.ssl.SSLProtocolException Read timed out
ERROR: An error occurred during the fetch of repository 'remotejdk11_linux_aarch64':
   java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu11.31.15-ca-jdk11.0.3/zulu11.31.15-ca-jdk11.0.3-linux_aarch64.tar.gz] to /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/remotejdk11_linux_aarch64/zulu11.31.15-ca-jdk11.0.3-linux_aarch64.tar.gz: Read timed out
INFO: Call stack for the definition of repository 'remotejdk_linux' which is a http_archive (rule definition at /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:120:1
WARNING: Download from https://mirror.bazel.build/openjdk/azul-zulu-9.0.7.1-jdk9.0.7/zulu9.0.7.1-jdk9.0.7-linux_x64-allmodules.tar.gz failed: class javax.net.ssl.SSLProtocolException Read timed out
ERROR: An error occurred during the fetch of repository 'remotejdk_linux':
   java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu-9.0.7.1-jdk9.0.7/zulu9.0.7.1-jdk9.0.7-linux_x64-allmodules.tar.gz] to /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/remotejdk_linux/zulu9.0.7.1-jdk9.0.7-linux_x64-allmodules.tar.gz: Read timed out
INFO: Call stack for the definition of repository 'remotejdk11_win' which is a http_archive (rule definition at /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:249:1
WARNING: Download from https://mirror.bazel.build/openjdk/azul-zulu11.2.3-jdk11.0.1/zulu11.2.3-jdk11.0.1-win_x64.zip failed: class javax.net.ssl.SSLProtocolException Read timed out
ERROR: An error occurred during the fetch of repository 'remotejdk11_win':
   java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu11.2.3-jdk11.0.1/zulu11.2.3-jdk11.0.1-win_x64.zip] to /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/remotejdk11_win/zulu11.2.3-jdk11.0.1-win_x64.zip: Read timed out
INFO: Call stack for the definition of repository 'remotejdk11_linux' which is a http_archive (rule definition at /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:216:1
WARNING: Download from https://mirror.bazel.build/openjdk/azul-zulu11.2.3-jdk11.0.1/zulu11.2.3-jdk11.0.1-linux_x64.tar.gz failed: class javax.net.ssl.SSLProtocolException Read timed out
ERROR: An error occurred during the fetch of repository 'remotejdk11_linux':
   java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu11.2.3-jdk11.0.1/zulu11.2.3-jdk11.0.1-linux_x64.tar.gz] to /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/remotejdk11_linux/zulu11.2.3-jdk11.0.1-linux_x64.tar.gz: Read timed out
INFO: Call stack for the definition of repository 'remote_java_tools_darwin' which is a http_archive (rule definition at /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:280:1
WARNING: Download from https://mirror.bazel.build/bazel_java_tools/releases/javac11/v6.1/java_tools_javac11_darwin-v6.1.zip failed: class javax.net.ssl.SSLProtocolException Read timed out
WARNING: Download from https://github.com/bazelbuild/java_tools/releases/download/javac11-v6.1/java_tools_javac11_darwin-v6.1.zip failed: class javax.net.ssl.SSLProtocolException Read timed out
ERROR: An error occurred during the fetch of repository 'remote_java_tools_darwin':
   java.io.IOException: Error downloading [https://mirror.bazel.build/bazel_java_tools/releases/javac11/v6.1/java_tools_javac11_darwin-v6.1.zip, https://github.com/bazelbuild/java_tools/releases/download/javac11-v6.1/java_tools_javac11_darwin-v6.1.zip] to /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/remote_java_tools_darwin/java_tools_javac11_darwin-v6.1.zip: Read timed out
ERROR: java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu11.31.15-ca-jdk11.0.3/zulu11.31.15-ca-jdk11.0.3-linux_aarch64.tar.gz] to /private/var/tmp/_bazel_gdelimpaltadak/429d1749cb426430efafa1a1c9a8c35c/external/remotejdk11_linux_aarch64/zulu11.31.15-ca-jdk11.0.3-linux_aarch64.tar.gz: Read timed out
Loading: loading...

**Comment by soonho-tri** [comment]
What do you have when you run `bazel version`? If it's not `2.0.0`, can you run `brew upgrade` and see if that fixes the problem?

**Comment by GDelimpa** [comment]
I upgraded my bazel version to 2.0.0 but the above problem still remains...
Moreover, when I run brew upgrade, I also get the following dreal-related error:

> ==> Upgrading dreal-deps/ibex/ibex@2.6.5 
==> Installing dependencies for dreal-deps/ibex/ibex@2.6.5: dreal-deps/coinor/clp
Error: clp is already installed from homebrew/core!
Please `brew uninstall clp` first."

This has come up again in the past.

**Comment by soonho-tri** [comment]
1) clp: Please run `brew uninstall ibex@2.6.5`. Also make sure that `brew list | grep "ibex@"` only returns `ibex@2.7.4`.

2) bazel issue: Can you try the following to check if you can build an official example repo using your bazel?

```bash
git clone https://github.com/bazelbuild/examples
cd examples/cpp-tutorial/stage1
bazel build //...
```

**Comment by GDelimpa** [comment]
I carried out both successfully.

**Comment by soonho-tri** [comment]
Do you still have the problem with dReal though?

**Comment by GDelimpa** [comment]
It worked, I successfully built dreal! Thanks for the help!

**Comment by soonho-tri** [comment]
Great!
