### ISSUE TITLE
unexpected symbol when encountering xor

### ISSUE THREAD

**Issue by leokarti** [dreal/dreal4#168]
hi I am trying to use the dreal solver but when it encounters a xor it gives and error saying "unexpected symbol".  I am running the docker version. any help would be appreciated.
I have attached the file as well

[666.zip](https://github.com/dreal/dreal4/files/4045677/666.zip)

**Comment by scungao** [comment]
You can check the operators supported right now at https://github.com/dreal/dreal4/blob/master/dreal/smt2/scanner.ll#L166

**Comment by soonho-tri** [comment]
As @scungao mentioned above, we do not support `xor`. You need to rewrite it using `and` and `or`.

**Comment by soonho-tri** [comment]
FYI, #211 implements `xor` support.
