### ISSUE TITLE
Get all solutions of lattice points close to circle

### ISSUE THREAD

**Issue by goretkin** [dreal/dreal4#170]
```python
from dreal import *
import numpy as np
import matplotlib.pyplot as plt

x0 = Variable("x0", Variable.Int)
y0 = Variable("y0", Variable.Int)
dx = Variable("dx")
dy = Variable("dy")
c = Variable("c")
s = Variable("s")
f = And(
  c**2 + s**2 == 10**2,
  x0 + dx == c,
  y0 + dy == s,
  -0.5 <= dx, dx <= 0.5,
  -0.5 <= dy, dy <= 0.5
)

sols = []

while True:
  print(len(sols))
  ans = CheckSatisfiability(f, 0.00000001)

  if ans is None:
    print("no more")
    break

  vx = ans[x0]
  vy = ans[y0]
  if (vx.is_degenerated() and vy.is_degenerated()):
    vx = vx.ub()
    vy = vy.ub()
    f = And(f, x0 != vx, y0 != vy)
    sols.append((int(vx), int(vy)))
  else:
    print("not degen")


sols_p = np.array(sols) - np.min(sols, 0)
bmp = np.zeros(tuple(np.max(sols_p, 0) + 1))
for sol in sols_p:
  bmp[sol[0],sol[1]] = 1

plt.imshow(bmp)
plt.show()
```

produces these 14 solutions:
```
[(-8, 6),
 (-9, 5),
 (-7, 7),
 (-6, 8),
 (-5, 9),
 (-10, 2),
 (-3, 10),
 (-4, -9),
 (-1, -10),
 (9, 3),
 (8, -6),
 (7, -7),
 (10, 1),
 (6, -8)]
```
Which plotted look like (ignoring the axes offset):
![Figure_1](https://user-images.githubusercontent.com/581043/74136719-968d5100-4bbc-11ea-9059-ddfc89ac5655.png)

How can I get the rest of the solutions? The plot should look like a blocky circle, indicating all the squares through which the circle of radius 10 passes.

**Comment by scungao** [comment]
When you write f=And(f, x0!=vx, y0!=by), it should be f=And(f, Or(x0!=vx,
y0!=by)).

**Comment by soonho-tri** [comment]
<img width="522" alt="Screen Shot 2020-02-10 at 11 03 19 AM" src="https://user-images.githubusercontent.com/20779767/74166681-fd2e6100-4bf4-11ea-8b60-8bc3bf2a9045.png">

@scungao , correct. Closing the issue.

**Comment by goretkin** [comment]
Thanks for catching my mistake. And thanks for posting the plot!
