### ISSUE TITLE
https://dl.bintray.com/dreal/dreal/dreal_4.19.10.3_amd64.deb does not work on Ubuntu 16.04

### ISSUE THREAD

**Issue by ANogin** [dreal/dreal4#186]
It looks like it was compiled with a newer version of coinor-libclp-dev and expects to have libClpSolver.so.1, but 1.15.10-1build2 from Ubuntu 16.04 has only libClp.so.1 and no libClpSolver.so.1

**Comment by soonho-tri** [comment]
@ANogin , thanks for the report. Yes, I've made a mistake of building the `.deb` file on Ubuntu 18.04, which made it incompatible with <= 16.04. I'll update it by EOD today.

**Comment by soonho-tri** [comment]
Could you check https://dl.bintray.com/dreal/dreal/dreal_4.20.03.4_amd64.deb ?

**Comment by ANogin** [comment]
That one worked, thanks!
