### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by soonho-tri** [dreal/dreal4#187]
Release date: April 23, 2020
TODO:
 - [x] ibex PPA for 20.04
 - [x] setup script
  - libnlopt-cxx-dev
  - python2.7

**Comment by soonho-tri** [comment]
Closed by 8f479c7a42010e5426337f1a3d201d7cd116ee92
CI support: 3a3197232083404d0907d1452e9ac14ee9c30301

**Comment by dzufferey** [comment]
Hi,
I just upgraded to ubuntu 20.04 and tried to build dreal4. There may be a few issue on my side but I think some also come from the build/install script.

Both `install.sh` and 'install_prereqs.sh' try to install `.deb` with `apt-get install`.
That does not work. I get an error of the style `Download is performed unsandboxed as root as file`.
I think you need to use `dpkg -i` instead.

Also I tried to build from the sources and I got an error related to the python bindings:
```
RROR: /home/zufferey/tools/dreal4/dreal/BUILD.bazel:58:1: C++ compilation of rule '//dreal:_dreal_py.so' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 105 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/pybind11/include/pybind11/pytypes.h:12,
                 from external/pybind11/include/pybind11/cast.h:13,
                 from external/pybind11/include/pybind11/attr.h:13,
                 from external/pybind11/include/pybind11/pybind11.h:44,
                 from external/pybind11/include/pybind11/functional.h:12,
                 from dreal/dreal_py.cc:8:
external/pybind11/include/pybind11/detail/common.h:112:10: fatal error: Python.h: No such file or directory
  112 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
```
Both `python2.7-dev` and `python3-dev` are installed on my machine. So I'm not sure what I'm missing.

BTW, on some unrelated note. Is it still possible to use dreal for optimization (dop) ?

Thanks

**Comment by soonho-tri** [comment]
Thanks for the report, @dzufferey. I'll check things and get back to you.

**Comment by soonho-tri** [comment]
I have created a fresh VM with Ubuntu-20.04 ISO and tested those scripts.

1) I do not have `Download is performed unsandboxed as root as file` error. [This Github CI job](https://github.com/dreal/dreal4/runs/648645947?check_suite_focus=true) does not report the error either. Searching S&O, I've found this entry, https://askubuntu.com/questions/908800/what-does-this-synaptic-error-message-mean. I guess it might solve your problem?

2) `Python.h: No such file or directory`: I think your system does not have `libpython3-dev`. Can you check? I assume that `python` executes `python3`. If it runs `python2`, you need `libpython2.7-dev`.

3) `dop`: Yes. We've just dropped that extension (`.dop`) and extended `.dr` format. PTAL https://github.com/dreal/dreal4/blob/master/dreal/test/dr/constrained_opt_mishra_bird.dr .

**Comment by dzufferey** [comment]
1. Thanks or the S&O link, this is not the issue. There was rw access. I also tried to create a specific folder with the rights but this does not help. Here is the result when I commented out the line which removes the `deb`.
    ```
    ls -alF /home/zufferey/tmp/asdf/test/
    drwxr-xr-x 2 _apt     root        4096 May  6 14:25 ./
    drwxrwxrwx 3 zufferey zufferey    4096 May  6 14:21 ../
    -rw-r--r-- 1 root     root     1244446 Apr 19 08:55 dreal_4.20.04.1_amd64.deb
    ```
    I'll try to search some more.
2. It was a bazel issue. I had another bazel installation but of bazel 3.1.0. I downgraded to 3.0.0 and it works.
3. Thanks.

**Comment by soonho-tri** [comment]
2) Just updated the scripts to use `bazel-3.1.0`. I'll check the Ubuntu-focal CI how it works with the new version.

**Comment by soonho-tri** [comment]
> I'll check the Ubuntu-focal CI how it works with the new version.

It works.

**Comment by dzufferey** [comment]
I tried with another machine. On the 2nd machine, bazel 3.1.0 runs fine. On the other hand, the `apt` error shows on both machines.

Both machines were originally installed with ubuntu 16.10 and 17.04 and continuously upgraded (no fresh install). So I suspect my problems are related to the old config and not about dreal4.

I think you can mark the issue as resolved. If I figure out what is going on and there is more to it, I'll ping you.

Thanks for the help.

**Comment by soonho-tri** [comment]
https://github.com/dreal/dreal4/commit/c7d83e324f82e0deb0b92108b3e32fb555303bdd switches from `apt` to `dpkg` to install `.deb`. It'd be great if you can the latest `master`.

> I think you can mark the issue as resolved.

OK.

**Comment by dzufferey** [comment]
The script runs fine. I can find dreal in `/opt/dreal/4.20.04.1/`. However, my $PATH does get updated so it does not contains the executable. Actually, $PATH does not contains anything from `/opt/`.

**Comment by dzufferey** [comment]
I did a quick search about `deb` archive and `$PATH` extension but I could not find anything.
Would it make sense to have the prefix `/usr/` rather than `opt/dreal/$version/`?
Beyond the path there are the `include` and `lib` as well.

**Comment by soonho-tri** [comment]
`/opt` is reserved for all the software and add-on packages that are not part of the default installation.

We ask users to either spell out the full path `/opt/dreal/<version>/bin/dreal`, update their `PATH` variable, or make a symbolic link to it.

> Beyond the path there are the include and lib as well.

See https://github.com/dreal/dreal4/#how-to-use-dreal-as-a-library for details. In case of using cmake, we provide [an example repository](https://github.com/dreal/dreal-cmake-example-project) which include [FindDreal.cmake](https://github.com/dreal/dreal-cmake-example-project/blob/master/cmake/modules/FindDreal.cmake) file.

**Comment by dzufferey** [comment]
My bad, I should have read the text again until the end. I just ran the script and forgot to turn my brain on. :)

**Comment by soonho-tri** [comment]
Not a problem. Let me know if you find further issues.
