### ISSUE TITLE
worklist fixpoint

### ISSUE THREAD

**Issue by soonho-tri** [dreal/dreal4#195]
It has an issue when there is a Boolean variable in a box. I'm working on a fix.

Related: #194, #192, #190, #189, #188

**Comment by rainoftime** [comment]
A query without Boolean variables also has the issues (https://github.com/dreal/dreal4/issues/192, https://github.com/dreal/dreal4/issues/189)

**Comment by soonho-tri** [comment]
Fixed by #196
