### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by saramohammadinejad** [dreal/dreal4#203]
When I import dreal in python on Mac I get this error:

from dreal._dreal_py import *
ImportError: dlopen(/Users/saramohamadi/Desktop/DiffVerifyRNN/test/venv/lib/python3.7/site-packages/dreal/_dreal_py.so, 2): Library not loaded: @loader_path/../_solib_darwin/_U_S_S_Cdreal_Ushared_Ulibrary___U/libdreal.so
  Referenced from: /Users/saramohamadi/Desktop/DiffVerifyRNN/test/venv/lib/python3.7/site-packages/dreal/_dreal_py.so
  Reason: image not found

Anyone has faced this issue and knows how to solve it?

**Comment by soonho-tri** [comment]
What do you have when you run `/Users/saramohamadi/Desktop/DiffVerifyRNN/test/venv/lib/python3.7/site-packages/dreal/*.so`?

Also, please check you are using the latest version of dreal python bindings. Doing something like `pip install dreal --upgrade` should do the work.

**Comment by saramohammadinejad** [comment]
When I run that:

python3 /Users/saramohamadi/Desktop/DiffVerifyRNN/test/venv/lib/python3.7/site-packages/dreal/*.so
  File "/Users/saramohamadi/Desktop/DiffVerifyRNN/test/venv/lib/python3.7/site-packages/dreal/_dreal_py.so", line 1
SyntaxError: Non-UTF-8 code starting with '\xcf' in file /Users/saramohamadi/Desktop/DiffVerifyRNN/test/venv/lib/python3.7/site-packages/dreal/_dreal_py.so on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

And also this: pip install dreal --upgrade:
Requirement already up-to-date: dreal in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (4.20.4.1)

**Comment by soonho-tri** [comment]
sorry, I meant: `ls /Users/saramohamadi/Desktop/DiffVerifyRNN/test/venv/lib/python3.7/site-packages/dreal/*.so`. There should be two `.so` files, `_dreal_py.so` and `libdreal.so`. Can you check if you have both?

If not, please check `pip uninstall dreal && pip install dreal` and see if it makes any changes.

**Comment by saramohammadinejad** [comment]
Yes, I have both .so files. I asked one of my friends to install dreal on his Mac. He also gets the same error when importing dreal into python.

**Comment by soonho-tri** [comment]
Have you installed dReal itself via homebrew? `brew install dreal` should do the job. It's a prerequisite for dreal's python bindings.

**Comment by saramohammadinejad** [comment]
Yes I did

**Comment by soonho-tri** [comment]
I guess I might need more information from your-side.

1) What's the output of `brew info dreal`?

2) Also `brew config`? Please feel free to remove any sensitive information from the raw output.

**Comment by saramohammadinejad** [comment]
running "brew info dreal" helped me understand some of the dependencies are not installed. I guess running the command "brew install dreal --only-dependencies" didn't install all the dependencies properly. Thanks for your help!

**Comment by soonho-tri** [comment]
Yeah.. I thought that we only need dependencies of dReal, not the dReal itself. So I wrote the current README.md as it is. I'll investigate the problem and fix either the doc or the bindings. Thanks for the report.

**Comment by soonho-tri** [comment]
FYI, I've just released `4.20.4.2` in PyPI. This one should be working only with dReal dependencies installed (no need to install dReal itself).

https://pypi.org/project/dreal/4.20.4.2

**Comment by saramohammadinejad** [comment]
Thanks! I also have another question: does dreal have parallelization? assume  I want to check satisfiability (ax+b<y). Can x and y be arrays? I mean instead of doing Sat(ax[0]+b<y[0]), Sat(ax[1]+b<y[1]),...separately, can we call sat(ax+b<y), where x and y are arrays?

**Comment by soonho-tri** [comment]
@saramohammadinejad , 

1) You can try this line https://github.com/dreal/dreal4/blob/master/dreal/api/test/cav18_benchmark.py#L30.

2) Note that `∃ x. [f₁(x) ∧ f₂(x)]` and `(∃ x. f₁(x)) ∧ (∃ x. f₂(x))` are not equivalent. So it's not correct to use an outer loop and check each `sat(f_i)` independently. You could do that for a disjunctive case though.

**Comment by saramohammadinejad** [comment]
Thanks a lot! I took a look at this benchmark, but I don't see any parallelization. Could you please explain more?

Here is what I'm doing:
1) computing the global min using a tool in Scipy 
2) Using dreal to check whether the global min is valid as follows:(the problem is that when the bounds become wide it becomes pretty slow)


f_sat_lower = And(-10<= x, x <= 7,
                      -6<= y, y <= 9,
                      -5 <= z, z <=14,
                      global_min > (exp(x + y) / (1 + exp(x + y))) * (z + 3) - (
                              exp(x) / (1 + exp(x))) * (z))
 result = CheckSatisfiability(f_sat_lower, 0.01)

**Comment by soonho-tri** [comment]
There is `CheckSatisfiability` which takes `Config` as an argument. So you need to first construct a `Config`.

```python
    config = Config()
    config.precision = 0.01
    config.number_of_jobs = number_of_jobs  # <- change this part
```

Then call `CheckSatisfiability(f_sat_lower, config)`.

**Comment by saramohammadinejad** [comment]
Thanks! May I ask what is the number of jobs?

**Comment by soonho-tri** [comment]
That's the number of CPUs that you want to use in parallelization.
