### ISSUE TITLE
Symbol not found: ___addtf3

### ISSUE THREAD

**Issue by thuang-power** [dreal/dreal4#205]
Hi!

I try to install dreal in anaconda where they have pip (but not pip3) function. I have tried that and it seems that dreal is installed in my virtual environment. However, "___addtf3" error appears. The bug info. is attached. I am wondering if pip and pip3 can achieve the same goal in the virtual environment?

Besides, I've also installed dreal outside the virtual environment by trying out the commands that you provided. However, a similar issue also appears. The bug info. is also attached.

After searching online, I realize that "___addtf3" error seems to be a general issue and have tried to update "scipy" based on suggestions in some websites. But it cannot solve the problem.

Here are the error info
<img width="937" alt="Error in Anaconda" src="https://user-images.githubusercontent.com/46176353/81422966-c0a1d100-9121-11ea-9c29-e8f12f4dbdda.png">
<img width="861" alt="Error in system" src="https://user-images.githubusercontent.com/46176353/81422967-c13a6780-9121-11ea-8f7e-c84ca2b3038c.png">

**Comment by soonho-tri** [comment]
Hi,

- which version of macOS are you using?
- can you run “brew upgrade” and “brew doctor”? Does it report any issue regarding “gcc”?

**Comment by thuang-power** [comment]
Hi,
For "brew update", no issue is reported. But for "brew doctor", there are some warning on "gcc" (attached).
<img width="607" alt="Screen Shot 2020-05-08 at 12 10 13" src="https://user-images.githubusercontent.com/46176353/81425473-acf86980-9125-11ea-902a-e4619dc4cae1.png">

**Comment by soonho-tri** [comment]
I guess “brew link gcc” fixes the problem.

**Comment by thuang-power** [comment]
> I guess “brew link gcc” fixes the problem.

Many thanks! It solves the issue.

**Comment by soonho-tri** [comment]
Great!
