### ISSUE TITLE
Support `get-value` command of SMTLib

### ISSUE THREAD

**Issue by LeventErkok** [dreal/dreal4#207]
Would be great if `dReal` supported SMTLib's `get-value` command. This would enable tools built on top of SMT solvers to communicate with dReal easily.

Note that while `get-model` can be used in general, `get-value` is much more efficient and much easier to use when there are thousands of variables and we only care about the value of a few.

**Comment by soonho-tri** [comment]
Thanks for the suggestion. I'll check things and start working on it.

**Comment by soonho-tri** [comment]
The support is added by 5996adf9161ba706afd458b41eae3e2d9e4bc497.

**Comment by LeventErkok** [comment]
@soonho-tri 

Thanks..

Will you be doing a brew release so I can give this a test? Alternatively, is there a brew formula that builds from sources?

**Comment by soonho-tri** [comment]
> Will you be doing a brew release so I can give this a test? 

Updated. https://github.com/dreal/homebrew-dreal/commit/8b5f02620af08d35863cdaa0198086f4a91f3892

**Comment by LeventErkok** [comment]
Thanks!
