### ISSUE TITLE
Maximize Int almost correct

### ISSUE THREAD

**Issue by johndoe888** [dreal/dreal4#210]
dReal version: 4.20.04.1 
Ubuntu version: 20.04

------------------------------
SMT2 script:
------------------------------
(declare-const i Int)
(assert (< i 100))
(assert (< 1 i))
(maximize i)
(check-sat)
(get-model)

------------------------------
Result:
------------------------------
delta-sat with delta = 0.001
(model
  (define-fun i () Int **_98_**)
)

------------------------------
Expected:
------------------------------
delta-sat with delta = 0.001
(model
  (define-fun i () Int **_99_**)
)

**Comment by soonho-tri** [comment]
Fixed by 2e8698873a709ff16e3962b8d82bd9c83579d2c3
