### ISSUE TITLE
SMTLib: Support distinct

### ISSUE THREAD

**Issue by LeventErkok** [dreal/dreal4#221]
In SMTLib,

```
(distinct a b c)
```
is a shorthand for stating `a`, `b`, and `c` are all different from each other. It can take an arbitrary number of arguments: In the simple case of two arguments, it means `a != b`

Would be great if `dReal` supported distinct in general.

As a workaround, it'd be at least great to have the 2-argument form; as most upstream tools use this as a way of stating two things are not-equal; instead of the double call to `not` and `=`.

**Comment by soonho-tri** [comment]
`(distinct a  b)` is equivalent to `a != b` which is `|a - b| > 0`. Its delta-weakening is `|a - b| >= -delta`. As `delta > 0`, `|a - b| >= -delta` is a tautology and dReal can assign the same value to `a` and `b` (e.g. `a = 1`, `b = 1`).

I am afraid that supporting `distinct` can mislead users and it is better not to support this syntax to avoid confusion.

**Comment by soonho-tri** [comment]
FYI, we already support `xor` for formulas.

**Comment by LeventErkok** [comment]
Good point about the confusion on `distinct.` But I'm not sure if it's any worse than the fact that `x != y` being satisfiable with `x` and `y` being assigned the exact same value. (Supporting one but not the other seems rather arbitrary.)

But I do agree, perhaps it's perfectly fine to skip this one. Feel free to close this ticket as you see fit.

**Comment by soonho-tri** [comment]
OK. I'm closing this one now.
