### ISSUE TITLE
The example on the landing page encodes a different problem than what's stated

### ISSUE THREAD

**Issue by LeventErkok** [dreal/dreal4#224]
On http://dreal.github.io/, the Flyspeck example as given by the formula has the following rhs:

```
    -0.591 - 0.0331 x_2 + 0.506 + 1.0
```

But the given SMTLib encoding's right-hand side is actually:

```
   0.591 - 0.0331 x_2 + 0.506 + 1.0
```

(Note the sign of the literal `0.591`.)

So, either the formula has the sign-flipped, or the SMTLib rendering of it has the incorrect sign.

The good news is that even after flipping the sign on the SMTLib script it remains `unsat`. (Which I suppose suggests the formula can be strengthened to state something much more strict, but that's besides the point.)

Would be good to make those two match!

(Incidentally, and if it is of any interest, this is how it's coded using SBV/Haskell: https://github.com/LeventErkok/sbv/blob/master/Documentation/SBV/Examples/DeltaSat/DeltaSat.hs#L23-L35)

**Comment by soonho-tri** [comment]
Thanks for the report, it's fixed by https://github.com/dreal/dreal.github.io/commit/9a7ae37de7d2856cb213316b0b1dcbaae35b8680.

> (Incidentally, and if it is of any interest, this is how it's coded using SBV/Haskell: 
> https://github.com/LeventErkok/sbv/blob/master/Documentation/SBV/Examples/DeltaSat/DeltaSat.hs#L23-L35)

Awesome!

**Comment by LeventErkok** [comment]
Great! Thanks for the quick fix.

I should note that the appearance of the literal `-7.0` is not strictly valid SMTLib either, but I suppose it can be considered a dReal extension. Strictly speaking

```
(set-option :produce-models true)
(set-logic ALL)
(declare-fun -7.0 () Int)
(assert (= -7.0 0))
(check-sat)
(get-model)
```

is a valid (yet very confusing!) SMTLib script, and CVC4, Mathsat, yices, etc. all accept it just fine. (Though z3 does complain about it incorrectly; but perhaps that's for the best!)

**Comment by soonho-tri** [comment]
Good point. We will take care of it when we work on #153.
