### ISSUE TITLE
Support `define-fun`

### ISSUE THREAD

**Issue by LeventErkok** [dreal/dreal4#225]
Another SMTLib2 nicety. The sequence:

```
(declare-fun s0 () Int)
(assert (= s0 1))
```

can be abbreviated to:

```
(define-fun s0 () Int 1)
```

This makes the benchmarks generated easier to read, and also can be taken advantage of internally by tools as they are essentially constants. (Easily discoverable by constant-folding, but helpful nonetheless.) But their main use case is to simplify generation of benchmarks, and reduce interprocess communication as it compresses two SMTLib commands into one.

Not an absolute must, but would be good to support this abbreviation. Almost all other solvers do.

**Comment by soonho-tri** [comment]
I believe this feature is already implemented. Can you run dReal with the following smt2 file?

```smt2
(set-logic QF_NRA)
(declare-fun s0 () Int)
(assert (= s0 1))
(check-sat)
(exit)
```

**Comment by soonho-tri** [comment]
Please ignore the deleted comment, but try the following:
```smt2
(set-logic QF_NRA)
(set-option :smtlib2_compliant true)
(define-fun s0 () Int 1)
(assert (= s0 1))
(check-sat)
(get-value (s0))
(exit)
```

**Comment by LeventErkok** [comment]
Quite right! I must've somehow confused myself to think it wasn't supported. Sorry about the noise!

**Comment by soonho-tri** [comment]
No problem. Thanks for checking things!
