### ISSUE TITLE
Unable to verify hyperbolic identity 

### ISSUE THREAD

**Issue by remysucre** [dreal/dreal4#230]
I couldn't get the following program to return `unsat`: 

```
(set-logic QF_NRA)
(declare-fun a () Real)

(assert (not (= (* (cosh a) (cosh a)) (+ 1.0 (* (sinh a) (sinh a))))))
(check-sat)
```

The identity comes from wikipedia's page on [hyperbolic functions](https://en.wikipedia.org/wiki/Hyperbolic_functions#Useful_relations), and it seems to be a pretty standard one (similar to the Pythagorean trigonometric identity). 
I tried tuning the precision and bounding `a`, but dreal always manages to find a solution. Is this identity just too "badly behaved" to be verified?

**Comment by scungao** [comment]
Yes, equalities are not delta-robust for any positive delta.

**Comment by remysucre** [comment]
I see, thank you!
