### ISSUE TITLE
Error with bazel 4.0 rc2

### ISSUE THREAD

**Issue by jwnimmer-tri** [dreal/dreal4#231]
After installing https://releases.bazel.build/4.0.0/rc2/index.html, in the Drake build I see: `ERROR: .../external/dreal/third_party/com_github_google_kythe/tools/build_rules/lexyacc.bzl:27:64: invalid escape sequence: \.. You can enable unknown escape sequences by passing the flag --incompatible_restrict_string_escapes=false`.  This is using `4.20.09.1`.

**Comment by soonho-tri** [comment]
Thanks for the report, Jeremy. I'll take a look.

**Comment by soonho-tri** [comment]
It should be fixed in https://github.com/dreal/dreal4/releases/tag/4.20.12.1.

**Comment by soonho-tri** [comment]
Fixed by 1881f550609d058ae3a2314cdef21dd8b5f3260d
