### ISSUE TITLE
Where can I learn the introduction and usage of various functions in Dreal

### ISSUE THREAD

**Issue by LGM97** [dreal/dreal4#235]

**Comment by soonho-tri** [comment]
Please check the python examples in [this directory](https://github.com/dreal/dreal4/tree/master/dreal/test/python).
[C++ examples](https://github.com/dreal/dreal4/blob/master/dreal/api/test/api_test.cc) are available as well.

**Comment by LGM97** [comment]
I still can't find an explanation for some of these functions，such as 'CheckSatisfiability'. Where can i find it?

**Comment by soonho-tri** [comment]
You can check this header file: https://github.com/dreal/dreal4/blob/master/dreal/api/api.h#L10-L61
