### ISSUE TITLE
Defining own variable types 

### ISSUE THREAD

**Issue by fabianmarquart** [dreal/dreal4#236]
There does not seem to be any possibility to create own variable types, such as Variable.Bool or Variable.Real. It would be nice if I could create a type Variable.Complex consisted of two reals.

**Comment by soonho-tri** [comment]
To support complex arithmetic, one has to do more than adding a complex variable type. The necessary work includes extending the interval arithmetic and interval propagation. For now, we do not have a plan to do so.
