### ISSUE TITLE
Different answers from dReal to the same problem

### ISSUE THREAD

**Issue by baoluomeng** [dreal/dreal4#237]
For the same problem below, dReal gives different answers depending on the running command. Is this expected?

`(set-logic QF_NRA)`
`(declare-fun x1 () Real)`
`(assert (= (^ x1 2) 4))`
`(check-sat)`
`(get-model)`

If I run dReal on the terminal with the command "dreal t1.smt2", where t1.smt2 is the file name, I am getting the following answer:
`% dreal t1.smt2`
`delta-sat with delta = 0.001  
(model  
  (define-fun x1 () Real [-2, -2])  
)`

However, if I run dReal with the command "dreal t1.smt2 --model", dReal gives the following answer.
`% dreal t1.smt2 --model`
`delta-sat with delta = 0.001`
`x1 : [-2.000000000000000444, -1.999999999999999778]`
`(model`
`  (define-fun x1 () Real [-2.000000000000000444, -1.999999999999999778])`
`)`

I am using dReal v4.20.09.1 on macOS Catalina 10.15.3.

**Comment by soonho-tri** [comment]
Hi @baoluomeng , I think the two answers are essentially the same but the first one happens to use different precision when printing out the interval value. I'll check the code and get back to you.

**Comment by soonho-tri** [comment]
1.
```
delta-sat with delta = 0.001
(model
  (define-fun x1 () Real [-2.0000000000000004, -1.9999999999999998])
)
```

2.
```
delta-sat with delta = 0.001
x1 : [-2.0000000000000004, -1.9999999999999998]
(model
  (define-fun x1 () Real [-2.0000000000000004, -1.9999999999999998])
)
```
