### ISSUE TITLE
Bazel build failure

### ISSUE THREAD

**Issue by rgyen** [dreal/dreal4#240]
I was trying to build dreal4 from source using Bazel.
Since I needed a static version of dreal4 and no pre-built dreal4 static version is provided, I tried to built it from source.
Unfortunately, the README installation instructions from dreal4 github leads me to a dynamic version of dreal4. 
I could not follow the instructions.

What I did:

1. Download a latest version of dreal4 source from release tab ([here](https://github.com/dreal/dreal4/releases/tag/4.20.12.1)).
2. Download a latest version of nlopt source from [here](https://github.com/stevengj/nlopt/archive/v2.6.2.tar.gz).
2-1. Build the nlopt with `cmake -DCMAKE_INSTALL_PREFIX=$HOME/some_local_place -DBUILD_SHARED_LIBS=OFF ..`
3. Download a latest version of ibex source from [here](https://github.com/ibex-team/ibex-lib/archive/ibex-2.8.9.zip).
3-1. Build the ibex with `cmake -DCMAKE_INSTALL_PREFIX=$HOME/some_local_place -DBUILD_SHARED_LIBS=0 ..`
4. Goto the dreal4 directory and modify **dreal_workspace** in **dreal4/workspace.bzl** to support [2-1, 3-1] pkgconfigs
4-1. At the root directory of the dreal4, `bazel build //...`

And I got stuck with following error messages:

> INFO: Analyzed 526 targets (36 packages loaded, 2954 targets configured).
INFO: Found 526 targets...
ERROR: /home/ryu/workspace/maude-se/.build/dreal4/dreal/contractor/BUILD.bazel:14:1: C++ compilation of rule '//dreal/contractor:contractor' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 91 argument(s) skipped)
>
>Use --sandbox_debug to see verbose messages from the sandbox
In file included from dreal/contractor/contractor_ibex_polytope.cc:1:
./dreal/contractor/contractor_ibex_polytope.h:63:25: error: 'LinearizerCombo' is not a member of 'ibex'; did you mean 'LinearizerCompo'?
   63 |   std::unique_ptr<ibex::LinearizerCombo> linear_relax_combo_;
      |                         ^~~~~~~~~~~~~~~
      |                         LinearizerCompo
./dreal/contractor/contractor_ibex_polytope.h:63:25: error: 'LinearizerCombo' is not a member of 'ibex'; did you mean 'LinearizerCompo'?
   63 |   std::unique_ptr<ibex::LinearizerCombo> linear_relax_combo_;
      |                         ^~~~~~~~~~~~~~~
      |                         LinearizerCompo
./dreal/contractor/contractor_ibex_polytope.h:63:40: error: template argument 1 is invalid
   63 |   std::unique_ptr<ibex::LinearizerCombo> linear_relax_combo_;
      |                                        ^
./dreal/contractor/contractor_ibex_polytope.h:63:40: error: template argument 2 is invalid
dreal/contractor/contractor_ibex_polytope.cc: In constructor 'dreal::ContractorIbexPolytope::ContractorIbexPolytope(std::vector<dreal::drake::symbolic::Formula>, const dreal::Box&, const dreal::Config&)':
dreal/contractor/contractor_ibex_polytope.cc:55:43: error: 'LinearizerCombo' is not a member of 'ibex'; did you mean 'LinearizerCompo'?
   55 |   linear_relax_combo_ = make_unique<ibex::LinearizerCombo>(
      |                                           ^~~~~~~~~~~~~~~
      |                                           LinearizerCompo
dreal/contractor/contractor_ibex_polytope.cc:55:43: error: 'LinearizerCombo' is not a member of 'ibex'; did you mean 'LinearizerCompo'?
   55 |   linear_relax_combo_ = make_unique<ibex::LinearizerCombo>(
      |                                           ^~~~~~~~~~~~~~~
      |                                           LinearizerCompo
dreal/contractor/contractor_ibex_polytope.cc:56:23: error: 'ibex::LinearizerCombo' has not been declared
   56 |       *system_, ibex::LinearizerCombo::XNEWTON);
      |                       ^~~~~~~~~~~~~~~
dreal/contractor/contractor_ibex_polytope.cc:57:46: error: invalid type argument of unary '*' (have 'int')
   57 |   ctc_ = make_unique<ibex::CtcPolytopeHull>(*linear_relax_combo_);
      |                                              ^~~~~~~~~~~~~~~~~~~
INFO: Elapsed time: 22.599s, Critical Path: 7.81s
INFO: 152 processes: 152 linux-sandbox.
FAILED: Build did NOT complete successfully

It seems that there were typos, `ibex::LinearizerCombo` (`ibex::LinearizerCompo` is correct), in files:
(a). `./dreal/contractor/contractor_ibex_polytope.h:63:25`
(b). `./dreal/contractor/contractor_ibex_polytope.h:63:40`
(c). `./dreal/contractor/contractor_ibex_polytope.h:55:43`
and `ibex::LinearizerCombo::XNEWTON` has not been declared in the `ibex` (found this at `dreal/contractor/contractor_ibex_polytope.cc:56:23`).

Is there something I missed? or Is there any pre-built static dreal4 provided?

**Comment by soonhokong** [comment]
Hi, please try this version of ibex:
https://github.com/dreal-deps/ibex-lib/tree/ibex-2.7.4_10 . This should fix
the LinearizeCombo error.

Best,
Soonho

**Comment by soonhokong** [comment]
FYI, ibex-lib is under LGPL so we, the dReal team, want to make sure that
our binary releases do not include ibex-lib.

>

**Comment by rgyen** [comment]
Thank you! It resolves my issue.

**Comment by soonho-tri** [comment]
Great!
