### ISSUE TITLE
The argument order to define-fun is not respected

### ISSUE THREAD

**Issue by baoluomeng** [dreal/dreal4#245]
Hello,

It seems like dReal is not respecting the argument order passed to functions. Below is an example. We are expecting the solution for R would be the same for line 9 and 10. But it seems like dReal inverses the arguments passed to `get_R`.  You can comment and uncomment line 9 and 10 to see the result.

`(set-logic QF_NRA)`
`(declare-fun a () Real)`
`(declare-fun b () Real)`
`(define-fun get_R ((x Real) (y Real)) Real`
`                   (* x (cos y)))`
`(assert (= a 12))`
`(assert (= b -0.7853981633974483))`
`(declare-fun R () Real)`
`;(assert (= R (* a (cos b))))`
`(assert (= R (get_R a b)))`
`(check-sat)`
`(get-model)`

 The version of dReal used is: dReal v4.20.09.1 (Release Build) for Mac and also the latest dReal docker image for Windows.

**Comment by soonho-tri** [comment]
@baoluomeng , thanks for the report. I've opened #246. I'll merge it when it passes the CI.

**Comment by baoluomeng** [comment]
> @baoluomeng , thanks for the report. I've opened #246. I'll merge it when it passes the CI.

Thank you, Soonho. Where can I get this update? Are you going to make a new release?

**Comment by soonho-tri** [comment]
@baoluomeng , `master` branch was already updated so you can check it out if you want. I'll release a new version soon as well.
