### ISSUE TITLE
Multivariable results in long computation time.

### ISSUE THREAD

**Issue by LGM97** [dreal/dreal4#253]
In my example, there are six variables, which leads to the calculation time of `CheckStatisfiability (condition, config)`  is too long to be applied. Config has been shrunk to 0.1. Are there any strategies to shorten the computing time?

**Comment by soonho-tri** [comment]
There is an option for parallelization (`-j <N>` option). In Python binding, set `config.number_of_jobs = <N>`.

If you can share the problem here (or via email), I can take a look during this weekend.

**Comment by soonho-tri** [comment]
Also, please check if you can provide a narrower domain for each variable. This usually helps.

**Comment by LGM97** [comment]
In my case, I want to verify whether the function obtained by neural networks meets the requirements. However, the calculation time is too long to be applied. So, I want to know if there any way to speed the calculation, such as reducing the accuracy of 'CheckSatisfiability'. Thank you very much for your help.
The code I am using is appended below:


def CheckLyapunov(x, f, V, ball_lb, ball_ub, config, epsilon):&nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; ball= Expression(0)
&nbsp; &nbsp; lie_derivative_of_V = Expression(0)
&nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; for i in range(len(x)):
&nbsp; &nbsp; &nbsp; &nbsp; ball += x[i]*x[i]
&nbsp; &nbsp; &nbsp; &nbsp; lie_derivative_of_V += f[i]*V.Differentiate(x[i])&nbsp;&nbsp;
&nbsp; &nbsp; ball_in_bound = logical_and(ball_lb*ball_lb <= ball, ball <= ball_ub*ball_ub)
&nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; condition = logical_and(logical_imply(ball_in_bound, V &gt;= 0),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;logical_imply(ball_in_bound, lie_derivative_of_V <= epsilon))
&nbsp; &nbsp; return CheckSatisfiability(logical_not(condition),config)



x1 = Variable("x1")
x2 = Variable("x2")
x3 = Variable("x3")
x4 = Variable("x4")
x5 = Variable("x5")
x6 = Variable("x6")


vars_ = [x1,x2,x3,x4,x5,x6]
config = Config()
config.use_polytope_in_forall = True
config.use_local_optimization = True
config.precision = 1e-1
config.number_of_jobs = 6
epsilon = 0
# Checking candidate V within a ball around the origin (ball_lb ≤ sqrt(∑xᵢ²) ≤ ball_ub)
ball_lb = 0.5
ball_ub = 1&nbsp;&nbsp;


result= CheckLyapunov(vars_, f, V_learn, ball_lb, ball_ub, config,epsilon)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dreal/dreal4"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月23日(星期三) 晚上10:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dreal/dreal4] Multivariable results in long computation time. (#253)





 
There is an option for parallelization (-j <N&gt; option). In Python binding, set config.number_of_jobs = <N&gt;.
 
If you can share the problem here (or via email), I can take a look during this weekend.

**Comment by LGM97** [comment]
In my case, I want to verify whether the function obtained by neural networks meets the requirements. However, the calculation time is too long to be applied. So, I want to know if there any way to speed the calculation, such as reducing the accuracy of 'CheckSatisfiability'. Thank you very much for your help.
The code I am using is appended below:

```
def CheckLyapunov(x, f, V, ball_lb, ball_ub, config, epsilon):   
    ball= Expression(0)
    lie_derivative_of_V = Expression(0)
   
    for i in range(len(x)):
        ball += x[i]*x[i]
        lie_derivative_of_V += f[i]*V.Differentiate(x[i]) 
    ball_in_bound = logical_and(ball_lb*ball_lb <= ball, ball <= ball_ub*ball_ub)
   
    condition = logical_and(logical_imply(ball_in_bound, V >= 0),
                           logical_imply(ball_in_bound, lie_derivative_of_V <= epsilon))
    return CheckSatisfiability(logical_not(condition),config)

x1 = Variable("x1")
x2 = Variable("x2")
x3 = Variable("x3")
x4 = Variable("x4")
x5 = Variable("x5")
x6 = Variable("x6")

vars_ = [x1,x2,x3,x4,x5,x6]
config = Config()
config.use_polytope_in_forall = True
config.use_local_optimization = True
config.precision = 1e-1
config.number_of_jobs = 6
epsilon = 0
# Checking candidate V within a ball around the origin (ball_lb ≤ sqrt(∑xᵢ²) ≤ ball_ub)
ball_lb = 0.5
ball_ub = 1 

result= CheckLyapunov(vars_, f, V_learn, ball_lb, ball_ub, config,epsilon)

```

**Comment by LGM97** [comment]
In my case, I want to verify whether the function obtained by neural networks meets the requirements. However, the calculation time is too long to be applied. So, I want to know if there any way to speed the calculation, such as reducing the accuracy of 'CheckSatisfiability'. Thank you very much for your help.
The code I am using is appended below:

```
def CheckLyapunov(x, f, V, ball_lb, ball_ub, config, epsilon):   
    ball= Expression(0)
    lie_derivative_of_V = Expression(0)
   
    for i in range(len(x)):
        ball += x[i]*x[i]
        lie_derivative_of_V += f[i]*V.Differentiate(x[i]) 
    ball_in_bound = logical_and(ball_lb*ball_lb <= ball, ball <= ball_ub*ball_ub)
   
    condition = logical_and(logical_imply(ball_in_bound, V >= 0),
                           logical_imply(ball_in_bound, lie_derivative_of_V <= epsilon))
    return CheckSatisfiability(logical_not(condition),config)

x1 = Variable("x1")
x2 = Variable("x2")
x3 = Variable("x3")
x4 = Variable("x4")
x5 = Variable("x5")
x6 = Variable("x6")

vars_ = [x1,x2,x3,x4,x5,x6]
config = Config()
config.use_polytope_in_forall = True
config.use_local_optimization = True
config.precision = 1e-1
config.number_of_jobs = 6
epsilon = 0
# Checking candidate V within a ball around the origin (ball_lb ≤ sqrt(∑xᵢ²) ≤ ball_ub)
ball_lb = 0.5
ball_ub = 1 

result= CheckLyapunov(vars_, f, V_learn, ball_lb, ball_ub, config,epsilon)

```

**Comment by soonho-tri** [comment]
> such as reducing the accuracy of 'CheckSatisfiability'

You use `config.precision = 1e-1`. If you want you can increase its value to `0.5` and `1.0` and check if it makes things faster.

FYI, you can delete the following lines:

```python
config.use_polytope_in_forall = True
config.use_local_optimization = True
```

Also please check if `config.use_polytope = True` helps.
