### ISSUE TITLE
Soft Constraints in dreal

### ISSUE THREAD

**Issue by kgoyal40** [dreal/dreal4#259]
Hi, Is there a way to enforce soft constraints in dreal, hopefully in the python bindings?

**Comment by soonho-tri** [comment]
It does not support soft constraints for now.

**Comment by kgoyal40** [comment]
Thank You. One more question, does it support the extraction of unsat cores?

**Comment by scungao** [comment]
Nope it doesn't do that right now.

**Comment by kgoyal40** [comment]
Hello, reviving this thread again. Is there any plan for having support for soft constraints or unsat cores in the future?
