### ISSUE TITLE
Python import dreal ibex library not found 

### ISSUE THREAD

**Issue by INPUTrrr0** [dreal/dreal4#260]
I have: dreal in ./anaconda3/lib/python3.7/site-packages (4.21.6.2) 
and ibex 2.8.9. 
I am using macOS 10.15.3 and Intel Core m3. 

When I want to import dreal in python, I get:
from dreal._dreal_py import *
ImportError: dlopen(/Users/theone/anaconda3/lib/python3.7/site-packages/dreal/_dreal_py.so, 2): Library not loaded: /usr/local/opt/ibex@2.7.4/lib/libibex.dylib
  Referenced from: /Users/theone/anaconda3/lib/python3.7/site-packages/dreal/_dreal_py.so
  Reason: image not found

In my /usr/local/opt/ directory I have "ibex" instead of "ibex@2.7.4". I also already have flex and bison. Does it mean I must have ibex 2.7.4 version for it to work? Thanks!!

**Comment by soonhokong** [comment]
Yes, you still need `ibex@2.7.4`. To install it, please run the following:

```bash
brew tap robotlocomotion/director
brew install ibex@2.7.4
```

**Comment by INPUTrrr0** [comment]
> Yes, you still need `ibex@2.7.4`. To install it, please run the following:
> 
> ```shell
> brew tap robotlocomotion/director
> brew install ibex@2.7.4
> ```

Perfect it worked!! Thank you so much!!

**Comment by soonhokong** [comment]
Good to know! Closing this issue.
