### ISSUE TITLE
Issue in using dReal4

### ISSUE THREAD

**Issue by ayeshamkzhh** [dreal/dreal4#262]
Hi,

I installed the pre-requisites as per the given instructions but I am still getting the following error when I try to use dReal inside python 3.6.9 and 3.10.0

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/asgr5/Desktop/dreal4/dreal/__init__.py", line 22, in <module>
    from dreal._dreal_py import *
ModuleNotFoundError: No module named 'dreal._dreal_py'

It would be great if you could help in resolving this issue.

**Comment by soonhokong** [comment]
Can you go outside of the `dreal4` directory (for example move to `~/tmp`) and run `python3` and execute the following lines?

```python
from dreal import *

x = Variable("x")
y = Variable("y")
z = Variable("z")

f_sat = And(0 <= x, x <= 10,
            0 <= y, y <= 10,
            0 <= z, z <= 10,
            sin(x) + cos(y) == z)

result = CheckSatisfiability(f_sat, 0.001)
print(result)
```

**Comment by ayeshamkzhh** [comment]
Many thanks. This worked inside dreal4/dreal directory.
