### ISSUE TITLE
dReal documentation

### ISSUE THREAD

**Issue by ayeshamkzhh** [dreal/dreal4#263]
Hi,

I am very new to dReal and SMt solvers. I was wondering if there exist any documentation for the commands and logics in dReal. This would be very helpful.

**Comment by soonhokong** [comment]
Hi, we have [a tool paper](http://www.cs.cmu.edu/~sicung/papers/dReal.pdf) and you can find more academic publications at https://scungao.github.io.

You can find more Python examples at https://github.com/dreal/dreal4/tree/master/dreal/test/python as well.
