### ISSUE TITLE
Dreal minimization at every point in interval 

### ISSUE THREAD

**Issue by alre5639** [dreal/dreal4#266]
I have a multi-variate function V(x,u) where x is all states of the system (for example [x,y,v,theta]) and u is a set of control inputs (for example [a, delta]) I would like to verify the following condition :
edit: I dont think my link is working so this equation is:
for all x in X, there exists a u in U where V(x,u) <0

![equation](http://www.sciweavers.org/tex2img.php?eq=%5Cforall%20x%20%5Cin%20X%2C%20%20%5Cexists%20u%20%5Cin%20U%20%3A%20V%28x%2Cu%29%20%3C%200%0A&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0)
That is, for all x contained with the set X, there exists a u in set U for which V(x,u) is negative. This can be reformulated to:

edit with equation link not working:
for all x in X, there exists a u in U where min(V(x,u)) <0
![equation](http://www.sciweavers.org/tex2img.php?eq=%5Cforall%20x%20%5Cin%20X%2C%20%20%5Cexists%20u%20%5Cin%20U%20%3A%20%5Cmin_%7Bu%20%5Cin%20U%7D%20V%28x%2Cu%29%20%3C%200%0A&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0)
Is there a way for the SMT solver to handle this condition? Essentially I need to check that all the states (contained withing some defined boundary) have a control(s) that will result in a negative function. I am able to verify that a function is N.D. in some interval using Dreal but unsure how to how to implement the additional minimization condition. Thank you

**Comment by soonhokong** [comment]
Hi @alre5639 , could you send me an email instead? We want to limit the issue tracker for bug reporting.

**Comment by soonhokong** [comment]
Closing this.
