### ISSUE TITLE
arch-based distro build help

### ISSUE THREAD

**Issue by johnviljoen** [dreal/dreal4#267]
I have looked at the pre-requisite and install scripts for Ubuntu, and I don't see any reason why it shouldn't work, except for libibex-dev.

This package is installed by adding a repository to apt on line 27 of dreal4/setup/ubuntu/20.04/install_prereqs.sh. I was wondering if this package is located on github or otherwise?

I am also not familiar with the Bazel compiler.

**Comment by soonhokong** [comment]
Hi,

1) IBEX: Please check out this branch, https://github.com/dreal-deps/ibex-lib/tree/ibex-2.7.4_14 . You can run the following to configure, build, and install.

```
# configure
CXXFLAGS=-std=c++11 ./waf configure \
      --prefix=/opt/libibex/2.7.4/ \
      --enable-shared \
       --with-solver \
       --with-affine-extended \
       --interval-lib=filib \
       --lp-lib=clp \
       --clp-path=<CLP PATH> 

# build
./waf build

# install
./waf install  # might need 'sudo'
```

Note that it's using the prefix, `/opt/libibex/2.7.4/`. This is where dReal is looking for ibex-lib.

2) Bazel: I don't think this is an issue. Just install bazel (https://archlinux.org/packages/?name=bazel) and run `bazel build`.

Please take a look at https://github.com/dreal/dreal4/blob/master/docs/BuildOnFedora.md . It would be great if you can write a similar doc (BuildOnArch.md) and open a PR.

**Comment by soonhokong** [comment]
Closing it for now.
