### ISSUE TITLE
Build problem MacOS - Ibex Installation

### ISSUE THREAD

**Issue by MominaSajid** [dreal/dreal4#282]
MacOS version: 12.5.1
Python Version: 3.8 & 2.7 (both installed)

I am getting the following error when I run the setup command """% ./setup/mac/install_prereqs.sh""" on the mac - i.e. install the ibex@2.7.4:

+ [[ 503 -eq 0 ]]
+ brew tap robotlocomotion/director
+ brew tap dreal/dreal
+ brew install dreal --only-dependencies --build-from-source

==> Installing dreal from dreal/dreal
==> Installing dependencies for dreal/dreal/dreal: robotlocomotion/director/ibex@2.7.4 and nlopt
==> Installing dreal/dreal/dreal dependency: robotlocomotion/director/ibex@2.7.4
==> ./waf configure --prefix=/opt/homebrew/Cellar/ibex@2.7.4/2.7.4_13 --enable-shared --with-optim --with-solver --with-affine-extended --interval-lib=filib --lp-lib=cl
Last 15 lines from /Users/younusu/Library/Logs/Homebrew/ibex@2.7.4/01.waf:
2022-09-11 09:50:23 +0000

./waf
configure
--prefix=/opt/homebrew/Cellar/ibex@2.7.4/2.7.4_13
--enable-shared
--with-optim
--with-solver
--with-affine-extended
--interval-lib=filib
--lp-lib=clp
--clp-path=/opt/homebrew/opt/clp

env: python2.7: No such file or directory
Do not report this issue to Homebrew/brew or Homebrew/core!

**Comment by soonhokong** [comment]
It doesn't support M1/M2 macs for now. Intel macs / x86_64 linux machines are supported.

**Comment by MominaSajid** [comment]
Can dreal be installed on windows?
________________________________

**Comment by soonhokong** [comment]
No. I know some people are using it via Docker though.
