### ISSUE TITLE
Is dReal working on m2 chips?

### ISSUE THREAD

**Issue by ThisIsJairo** [dreal/dreal4#295]
Hi!

I am wondering if dReal works on Apple m2 chips. I could install this solver on a MacBook with an i7 processor without problems, but I have not been able to install it on an m2 MacBook.

Many thanks in advance

**Comment by soonhokong** [comment]
Hi @ThisIsJairo , as of Feb 2023, all the interval packages that we can use with our interval pruning library IBEX are not supported in M1/M2 macs. That is a reason why we cannot build dReal on those macs for now.

**Comment by soonhokong** [comment]
Please follow https://github.com/dreal/dreal4/issues/295 if you want to get updates on this topic. Closing this one.
