### ISSUE TITLE
ImportError: libibex.so: cannot open shared object file

### ISSUE THREAD

**Issue by megaseptinh** [dreal/dreal4#300]
I encountered an issue while trying to import the dreal module in Python. The following error message was raised:

<img width="960" alt="image" src="https://github.com/dreal/dreal4/assets/140039929/173117e7-4834-49e1-af8f-daa2b5a562a1">

**Comment by soonhokong** [comment]
I think this is a problem in Google Colab. Please run the following line in a fresh Colab:
```
!sudo add-apt-repository ppa:ubuntu-mozilla-daily/ppa
```

It should give you the same error:
```
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 363, in <module>
    addaptrepo = AddAptRepository()
  File "/usr/bin/add-apt-repository", line 41, in __init__
    self.distro.get_sources(self.sourceslist)
  File "/usr/local/lib/python3.10/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Ubuntu/jammy
```

**Comment by zy1022ic** [comment]
I have encountered the same problem. I think this is because Colab just upgraded their default runtime to Ubuntu 22.04 LTS. One can access the old 20.04 LTS runtime (available until early August) from the Command Palette via the “Use fallback runtime version” command and it works.

**Comment by soonhokong** [comment]
> from the Command Palette via the “Use fallback runtime version” command and it works 

Please try the following steps:

1.
<img width="665" alt="Screenshot 2023-07-22 at 8 31 08 AM" src="https://github.com/dreal/dreal4/assets/403281/9d07e7de-6005-46a6-b758-a923f445ff30">

2.
<img width="561" alt="Screenshot 2023-07-22 at 8 31 21 AM" src="https://github.com/dreal/dreal4/assets/403281/f5c74396-9a90-4f86-987d-356b31a58ba8">

3.
<img width="596" alt="Screenshot 2023-07-22 at 8 31 26 AM" src="https://github.com/dreal/dreal4/assets/403281/312e5fe0-87be-49ae-a84f-aad3b5c9430d">
