### ISSUE TITLE
Integer Division

### ISSUE THREAD

**Issue by juliusbrehme** [dreal/dreal4#304]
Hello everyone,

I have the following code:
```
  Expression exp1{10};
  Expression exp2{3};
  Expression result{exp1/exp2};
```
The expected result of the Expression is 3, because of Integer Division, but I get 3.3333. 
If I do the following:
```
Expression result{10/3};
```
I get the expected 3. 

I don't know if that is intended or not.

Thanks in advance.

**Comment by soonhokong** [comment]
This is expected behavior. A constant expression holds a double value and division between expressions is handled not following the integer division rule.
