### ISSUE TITLE
Dreal4 Static Binary

### ISSUE THREAD

**Issue by ahmedirfan1983** [dreal/dreal4#32]
There is no option to build a static-binary of dReal4 in the bazel build.

Can you provide this feature ?
As an alternate solution, can you provide the static-binary in the Download section?

**Comment by soonho-tri** [comment]
dReal4 is under Apache-2.0 license and using LGPL packages. As a result, we're not supposed to release a static binary of it.

Did you find a problem when you follow [the installation instructions](https://github.com/dreal/dreal4#how-to-install-dreal)?

**Comment by ahmedirfan1983** [comment]
OK. That is reasonable for not distributing the static binary.

About the installation/building instructions, I am able to follow them. In fact, the compilation is successful. However, I need a statically-linked binary, which is not built.

**Comment by soonho-tri** [comment]
> About the installation/building instructions, I am able to follow them. In fact, the compilation is successful.

Great.

> However, I need a statically-linked binary, which is not built.

I guess there is a way to do it by changing our bazel build files, but I'm not knowledgeable about the details.

I'd copy a dynamically-linked binary with `.so` files in the same directory. That should work for most of the cases, I guess.

**Comment by ahmedirfan1983** [comment]
OK. I am also new to the bazel build system. :)

To explain why I want a static-binary, actually I need to run it over the cluster that uses Scientific Linux 7.2 (with gcc 4.8 and no clang support). To be able to run it I would need to do a lot of backporting :(

**Comment by soonho-tri** [comment]
I see. I'm really new to the SL distribution. But it seems that there is a way to install `g++-6` via http://linux.web.cern.ch/linux/scientific6/docs/softwarecollections.shtml . FYI, `clang` is not necessary to build dReal4. You can pass `--config gcc-6` when you run `bazel build` to use `g++-6` instead of the default `clang-3.9`.

**Comment by soonho-tri** [comment]
I'm closing this issue for now. Please feel free to add comments here though.
