### ISSUE TITLE
Error parsing smt

### ISSUE THREAD

**Issue by gomahajan** [dreal/dreal4#33]
When trying to parse this file: [uav_dreal_complete.txt](https://github.com/dreal/dreal4/files/1529258/uav_dreal_complete.txt)
dreal4 errors out while dreal3 works (returns unsat)

**Comment by soonho-tri** [comment]
Thanks for the report. The problem is that we don't handle `=>` symbol. I'll add it today.

**Comment by gomahajan** [comment]
Nice! Thanks.

**Comment by soonho-tri** [comment]
Almost done. Please let me know if we can add your file in our regression suite.

**Comment by gomahajan** [comment]
Oh yeah! You can definitely make it part of your tests.

**Comment by soonho-tri** [comment]
The test is added at https://github.com/dreal/dreal4/blob/master/dreal/test/smt2/uav.smt2. Please check out and try the latest version. It gives the expected `unsat` result.

**Comment by gomahajan** [comment]
It works. Thanks!
