### ISSUE TITLE
Exposing more Function and Variable constructors in the Python API

### ISSUE THREAD

**Issue by rohit507** [dreal/dreal4#73]
It would be nice to have access to more of the power of dreal in the python bindings themselves.
In particular the following constructs would be really nice to have handy: 

**Variable(name, type)** : A version of the "Variable(name, type, model_variable)"
with the model_variable fixed to True.

I think this would require you to add bindings for Type as well, but it seems like 
enums like that should be straightforward. 

**logical_implication(pre, post)** : I mean it can be assembled easily enough from the 
operators you provide, but you have "implies(formula &f1, Formula &f2)" lying around 
already. 

**logical_iff(a, b)** : Basically the same as above. 

**for_all(vars, formula)** : A binding to create a ForAll clause in a formula, possibly
with semantics that take a sequence of elements and allows the provided lambda to unpack them
internally. 

```Python


class UVar : 
  """
  A wrapper over initialization information for universally quantified variables.

  Initialization takes a name, and optionally, a type or box.
  """ 
  
  ...

def for_all ( vars, exp_gen) : 
  """
  vars : A list of all the uvars that we quantify over. 
  exp_gen : A function from a list of variables to an expression over those variables
  """
  
  ... 
  # Converts all the uvars in the list to normal variables
  # Runs the generator function with the now initialized variables
  # Calls the FormulaForAll constructor with the list of universal variables and the
  #   generated expression/formula. 


```

Which would allow for an interface like the following, that preserves useful guarantees 
about variable context. 

```Python

a = Variable("a", Real)
b = Variable("b", Real) 

f = for_all([UVar("x"), UVar("y", box=[10, 15], type=Real)], lambda uvars : 
       x, y = uvars 
 
       return logical_and(x = 2*y, a < x, b > x)
       )
```

A case I'd be particularly be interested in but didn't see in your test cases would allow
something like the following:

```Python

x_max = Variable("x_max")
x_min = Variable("x_min") 

f = for_all([UVar("x", box=[x_min,x_max])], lambda uvar : 
      return logical_and(sin(x) >= 0.2, cos(x) >= 0.2))

c = x_min - x_max # smaller intervals are lower values. 

Minimize(f,c)
```

It's easy enough to add the bounds within the generated function itself, so there's no
actual need for boxes that support this, but it would be a bit easier to read.

**Comment by rohit507** [comment]
Hmm, if you turn `ForAll([x], ForAll([y], expr))` into `ForAll([x,y], expr)` internally (or don't need to) then building things around python's `with` statement would work pretty well.

```python
f = with FA(box=[10,25]) as x, FA(type=Bool) as y: 
      # ...
      return logical_and( ... ) 
```
Of course, that's all just wrapping. I'd be happy to figure it out and submit a pull req if you do whatever implementation is easiest.

**Comment by rohit507** [comment]
Whoops, wrong button.

**Comment by soonho-tri** [comment]
Please check https://github.com/dreal/dreal4/commit/be0d32f46fbe5fcd0428ece5ace90f3d38094bc7.

**Comment by soonho-tri** [comment]
I've added `Variable::Type`, `logical_iff`, `logical_imply`, and `forall`. This `forall` is a straightforward binding of the C++ counterpart:

https://github.com/dreal/dreal4/blob/d11a900176c16070d1eefa2b7682d93e2fb4fd47/third_party/com_github_robotlocomotion_drake/drake/common/symbolic_formula.h#L259-L260

I think you can implement more utilities on top of this one.
