### ISSUE TITLE
Error while building from source: no such package `@ezoptionparser` 

### ISSUE THREAD

**Issue by amoudgl** [dreal/dreal4#91]
I am trying to build dreal4 from source by following [these steps](https://github.com/dreal/dreal4/blob/master/README.md#how-to-build). When I run `bazel build //...` it throws an error `no such package '@ezoptionparser//'`, view line 110 from [this log](https://pastebin.com/LsJB9hub). How do I fix this?  

Background: I am using Ubuntu 18.04. I followed the [installation steps](https://github.com/dreal/dreal4#how-to-install) from the README and I am able to reproduce the results of the README example in python2.7. I am trying to build dreal4 for python3 by following [this comment](https://github.com/dreal/dreal4/issues/69#issuecomment-377085510) but it throws the above error when I try to build from source (the first step in the comment).

**Comment by soonho-tri** [comment]
Can you check if https://github.com/bazelbuild/bazel/issues/4332#issuecomment-364557713 helps?

**Comment by amoudgl** [comment]
Thanks for your response. Just tried the comment, didn't work. 
Log: 
```bash
$ bazel build //...
Starting local Bazel server and connecting to it...
......
DEBUG: /home/aditi/.cache/bazel/_bazel_aditi/a27201366f97da62b0636a26a3eac955/external/bazel_tools/tools/build_defs/repo/http.bzl:43:9: ctx.attr.build_file //tools:pybind11.BUILD.bazel, path /home/aditi/Projects/dreal4/tools/pybind11.BUILD.bazel
ERROR: /home/aditi/Projects/dreal4/dreal/solver/BUILD.bazel:181:1: no such package '@pybind11//': java.io.IOException: Error downloading [https://github.com/pybind/pybind11/archive/v2.2.3.tar.gz] to /home/aditi/.cache/bazel/_bazel_aditi/a27201366f97da62b0636a26a3eac955/external/pybind11/v2.2.3.tar.gz: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty and referenced by '//dreal/solver:_dreal_solver_py.so'
ERROR: Analysis of target '//dreal/api:cav18_benchmark' failed; build aborted: no such package '@pybind11//': java.io.IOException: Error downloading [https://github.com/pybind/pybind11/archive/v2.2.3.tar.gz] to /home/aditi/.cache/bazel/_bazel_aditi/a27201366f97da62b0636a26a3eac955/external/pybind11/v2.2.3.tar.gz: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
INFO: Elapsed time: 15.118s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (39 packages loaded)
```

**Comment by soonho-tri** [comment]
> Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty and referenced

Can you check https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty/30699960#30699960 and try one of the answers? I suspect that it has nothing to do with dReal4.

**Comment by soonho-tri** [comment]
I guess that https://stackoverflow.com/a/50103533/2654527 is a relevant one.

> Currently, the bug has been fixed in Ubuntu Cosmic (18.10) but the backport of that fix to Ubuntu Bionic LTS (18.04) is waiting for issue 1770553. Confusingly, issue 1739631 has also been marked to affect Bionic, with a fix milestone of 18.04.1, and a named assignee. 18.04.1 is scheduled for the July 26th. Let's hope for the best!

In the worst case, you can wait for 15 days (July 26). But I guess you can find a workaround in that S&O entry.

**Comment by scungao** [comment]
Any chance that we could have an option for building just the library for API calls, in which ezoption parser is disabled? (I recall it giving trouble in the past as well?)

**Comment by soonho-tri** [comment]
My understanding is that because of the Ubuntu-18.04 issue, bazel fails to download any external packages that dReal depends on. This includes picosat, pybind11, fmt, spdlog, ezoptionparser, and gtest. It's hard to disable all of them. In particular, he needs `pybind11` to build python binding.

**Comment by soonho-tri** [comment]
If it turns out to be difficult to fix it, I can ship a Debian package which works on Ubuntu-18.04 and Python3. Please let me know if you want to use it.

**Comment by scungao** [comment]
Oh I see; I thought it's just the option parser. Yes a package for 18.04 and python3 would be great!

**Comment by soonho-tri** [comment]
@amoudgl , good to know. I'll close this issue.

@scungao , I'll try to make the package for 18.04 + python3 combo. But now it has lower priority ;-)
