### ISSUE TITLE
mac CI is broken because xcode9.4 ships java10 while homebrew bazel requires java8

### ISSUE THREAD

**Issue by soonho-tri** [dreal/dreal4#96]
It should be resolved when `bazel-0.16.1` is available in homebrew as it relaxes the java requirement to be `>=9`.

See: https://blog.travis-ci.com/2018-07-19-xcode9-4-default-announce#difference-between-current-default-xcode-83-image-and-upcoming-xcode-94-image
Related PR: https://github.com/Homebrew/homebrew-core/pull/31066

**Comment by buchgr** [comment]
Please see https://groups.google.com/forum/#!topic/bazel-discuss/3Ht26sWhMuA

**Comment by soonho-tri** [comment]
@buchgr , thanks for the update.

Close by 57f39fec22367f7154d7e75fadd8f4015dae796a and https://github.com/dreal/homebrew-dreal/commit/f503044b0daf03053c504e8cd386d1e26cbc7f44.
